/* Sterna core — the C ABI. GENERATED BY cbindgen, DO NOT EDIT.
 *
 * Regenerated by `cargo build -p tt-ffi`; CI fails if the committed copy and
 * the source disagree. Edit `crates/tt-ffi/src/lib.rs` instead.
 *
 * Copyright (c) the Sterna authors. 3-clause BSD; see LICENSE.
 */

#ifndef STERNA_H
#define STERNA_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Codepoints stored per cell: one base plus up to three combining marks.
 *
 * Tera Term grows its per-cell string without a fixed bound. A fixed array
 * keeps `Cell` POD and copyable across the C ABI, which the frontend seam
 * needs; marks past the third are dropped. Raise this if a real corpus wants
 * it — Hebrew and Thai stacks reach three, Zalgo text is not a use case.
 */
#define TT_CELL_TEXT_MAX 4

#define TT_ATTR_BOLD 1

#define TT_ATTR_UNDER 2

#define TT_ATTR_SPECIAL 4

#define TT_ATTR_BLINK 8

#define TT_ATTR_REVERSE 16

/**
 * `AttrSgrMask` (`buffer.h:58`) — the four attributes SGR itself can set, and
 * the only ones a selective erase leaves behind.
 */
#define TT_ATTR_SGR_MASK (((TT_ATTR_BOLD | TT_ATTR_UNDER) | TT_ATTR_BLINK) | TT_ATTR_REVERSE)

/**
 * The low byte, which is upstream's `Attr`. Masking only it is what
 * `attr &= ...` means in `buffer.c`.
 */
#define TT_ATTR_MASK 255

#define TT_ATTR2_FORE 256

#define TT_ATTR2_BACK 512

#define TT_ATTR2_COLOR_MASK (TT_ATTR2_FORE | TT_ATTR2_BACK)

/**
 * `Attr2Protect` (`buffer.h:66`) — DECSCA's bit. Selective erase skips a cell
 * carrying it, and SGR 0 deliberately does **not** clear it
 * (`vtterm.c:2178`).
 */
#define TT_ATTR2_PROTECT 1024

/**
 * Tera Term's `AttrDefaultFG` / `AttrDefaultBG` are both 0, not 7/0.
 */
#define TT_DEFAULT_FG 0

#define TT_DEFAULT_BG 0

/**
 * `BuffXMax` (`buffer.c:82`), which is `TermWidthMax` — **1000**, not the 500
 * this used to say. 500 is `TermHeightMax`, one line below it in
 * `tttypes.h:633`, and taking the wrong one made a 640-column terminal
 * silently half the width it asked for.
 */
#define TT_BUFF_X_MAX 1000

/**
 * `ts.ScrollBuffMax`'s default (`ttset.c:1213`, key `MaxBuffSize`), which is
 * the cap `BuffChangeTerminalSize` puts on the *height* (`buffer.c:4977`) —
 * a different quantity from [`Grid::scrollback_max`], which is how deep the
 * history actually goes. Conflating them means a terminal with its scroll
 * buffer turned off can only be one row tall.
 */
#define MAX_ROWS_DEFAULT 10000

/**
 * One column.
 */
#define TT_WIDTH_NARROW 0

/**
 * Two columns; the cell to the right is [`WIDTH_PAD`].
 */
#define TT_WIDTH_WIDE 1

/**
 * The right half of a wide character. Holds no text of its own.
 */
#define TT_WIDTH_PAD 2

/**
 * `IdLeftButton` … `IdButtonRelease` — `tttypes.h:674`.
 */
#define TT_BUTTON_LEFT 0

#define TT_BUTTON_MIDDLE 1

#define TT_BUTTON_RIGHT 2

#define TT_BUTTON_RELEASE 3

enum TtTermId
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    TT_TERM_ID_VT100,
    TT_TERM_ID_VT100_J,
    TT_TERM_ID_VT101,
    TT_TERM_ID_VT102,
    TT_TERM_ID_VT102_J,
    TT_TERM_ID_VT220,
    TT_TERM_ID_VT220_J,
    TT_TERM_ID_VT282,
    TT_TERM_ID_VT320,
    TT_TERM_ID_VT382,
    TT_TERM_ID_VT420,
    TT_TERM_ID_VT520,
    TT_TERM_ID_VT525,
    TT_TERM_ID_DUMB,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtTermId TtTermId;
#else
typedef uint32_t TtTermId;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which clock the `[time] ` prefix reads.
 *
 * `repr(u32)` because the C ABI names these variants directly rather than
 * keeping a second copy of the list that can drift — the same trade as
 * `tt_vt::Key`, and with the same consequence: reordering them is an ABI
 * break whose only symptom is the committed header's diff.
 */
enum TtLogTimestamp
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * No prefix.
     */
    TT_LOG_TIMESTAMP_NONE,
    /**
     * `%Y-%m-%d %H:%M:%S.%N` in local time — upstream's default format.
     */
    TT_LOG_TIMESTAMP_LOCAL,
    /**
     * The same, in UTC.
     */
    TT_LOG_TIMESTAMP_UTC,
    /**
     * Seconds since the log was opened, as `H:MM:SS.mmm`. The one that is
     * actually useful on a console: "how long after reset did it hang".
     */
    TT_LOG_TIMESTAMP_ELAPSED,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtLogTimestamp TtLogTimestamp;
#else
typedef uint32_t TtLogTimestamp;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * `MouseReportMode` — `tttypes.h:650`.
 *
 * The `repr(u32)` on this and its neighbours is not decoration: the C ABI
 * names these variants directly rather than keeping a second copy of the
 * list that can drift. See `tt-ffi`.
 *
 * One variable holds two unrelated protocols: the xterm family and DEC's
 * locator. They are mutually exclusive upstream because they share this
 * field, which is why `DECELR` and `DECSET 1000` cancel each other.
 */
enum TtTracking
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    TT_TRACKING_NONE,
    /**
     * DECELR. Reports through `CSI … & w` instead of the xterm formats.
     */
    TT_TRACKING_DEC_LOCATOR,
    /**
     * `DECSET 9` — press only, no modifiers, no release.
     */
    TT_TRACKING_X10,
    /**
     * `DECSET 1000` — press and release.
     */
    TT_TRACKING_VT200,
    /**
     * `DECSET 1001`. Upstream never implemented it; every path returns
     * without reporting, and DECRQM answers 4. Kept so the mode still
     * *displaces* whatever was active, which is observable.
     */
    TT_TRACKING_VT200_HL,
    /**
     * `DECSET 1002` — press, release, and motion while a button is down.
     */
    TT_TRACKING_BTN_EVENT,
    /**
     * `DECSET 1003` — all of the above plus motion with no button.
     */
    TT_TRACKING_ALL_EVENT,
    /**
     * `DECSET 14001`. Tera Term's own: `ESC } row,col CR`, press only, and
     * not a CSI at all.
     */
    TT_TRACKING_NET_TERM,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtTracking TtTracking;
#else
typedef uint32_t TtTracking;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a setting holds — enough for a dialog to pick a widget and no more.
 */
enum TtSettingKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * On or off. Note the value is spelled `on`/`off`, not `1`/`0`, and that
     * **the file's parse of it is not symmetric** — see [`TtSettingField`].
     */
    TT_SETTING_KIND_BOOL,
    TT_SETTING_KIND_INT,
    /**
     * An int with bounds: `min` and `max` are meaningful.
     */
    TT_SETTING_KIND_INT_RANGE,
    TT_SETTING_KIND_STR,
    /**
     * One of `choices` spellings, fetched with [`tt_settings_choice`].
     */
    TT_SETTING_KIND_ENUM,
    /**
     * Six numbers, `fg_r,fg_g,fg_b,bg_r,bg_g,bg_b`. Upstream's attributes
     * each carry their own foreground *and* background, which is why a colour
     * setting is a pair rather than one value.
     */
    TT_SETTING_KIND_COLOR2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtSettingKind TtSettingKind;
#else
typedef uint32_t TtSettingKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

enum TtEventKind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The screen changed. Coarse on purpose: a full 80x24 repaint measured
     * 3.9 ms on the target Qt, about 40x what a 115200 baud link can dirty,
     * so per-row damage is an optimisation to add when something asks for it.
     */
    TT_EVENT_KIND_DAMAGE = 0,
    /**
     * OSC 0 / OSC 2. `text` is the new title.
     */
    TT_EVENT_KIND_TITLE = 1,
    /**
     * A line break arrived. On a serial console this is how a host asks for
     * attention, and dropping it is a real loss of function.
     */
    TT_EVENT_KIND_BREAK = 2,
    /**
     * A byte arrived with a parity or framing error. `byte` is what came
     * through, kept rather than dropped: it is usually still readable, and
     * silently losing it makes a bad cable look like a bad program.
     */
    TT_EVENT_KIND_BAD_BYTE = 3,
    /**
     * The transport went away. Reported once; the screen is left alone,
     * because the text explaining why it dropped is the reason anyone looks.
     */
    TT_EVENT_KIND_DISCONNECTED = 4,
    /**
     * The session log could not be written and has been closed. `text` says
     * why. Reported once — a disk that filled up will not un-fill, and
     * retrying on every pump turns one problem into a stall.
     */
    TT_EVENT_KIND_LOG_FAILED = 5,
    /**
     * The **far end** says the terminal should be this size — `cols` and
     * `rows`. Telnet's NAWS, arriving backwards: RFC 1073 defines it
     * client-to-server, and a console server sends it the other way to say
     * what the equipment behind it actually is.
     *
     * **The core does not resize itself on this.** The window owns its own
     * size, and a grid that changed under the frontend would leave it
     * painting the wrong number of cells. Call [`tt_session_resize`] — and
     * resize the window with it — or ignore it.
     */
    TT_EVENT_KIND_RESIZE = 6,
    /**
     * A file transfer moved. Read [`tt_session_transfer_status`] for where
     * it has got to.
     */
    TT_EVENT_KIND_TRANSFER_PROGRESS = 7,
    /**
     * A file transfer ended, for any reason. Read
     * [`tt_session_transfer_result`] for how it went — and read it *on this
     * event*, because the next transfer replaces it.
     */
    TT_EVENT_KIND_TRANSFER_DONE = 8,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtEventKind TtEventKind;
#else
typedef uint32_t TtEventKind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which protocol. Mirrors `tt_xfer::Job`'s discriminants.
 */
typedef enum {
    TT_XFER_PROTOCOL_X_MODEM = 0,
    TT_XFER_PROTOCOL_Y_MODEM = 1,
    TT_XFER_PROTOCOL_Z_MODEM = 2,
    TT_XFER_PROTOCOL_KERMIT = 3,
    TT_XFER_PROTOCOL_B_PLUS = 4,
    TT_XFER_PROTOCOL_QUICK_VAN = 5,
    /**
     * Not a protocol: read the connection into a file until it goes quiet.
     * Receive only.
     */
    TT_XFER_PROTOCOL_RAW = 6,
} TtXferProtocol;

/**
 * A key with a terminal meaning. Names and grouping follow
 * `common/tttypes_key.h`, so a `KEYBOARD.CNF` reader can map onto them
 * directly.
 *
 * `repr(u32)` is not decoration: the C ABI names these variants directly rather
 * than keeping a second copy of the list that can drift. See `tt-ffi`.
 */
enum TtKey
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    TT_KEY_UP,
    TT_KEY_DOWN,
    TT_KEY_RIGHT,
    TT_KEY_LEFT,
    /**
     * The numeric keypad. In numeric mode these send their printed
     * character; in application-keypad mode, `SS3` plus a letter.
     */
    TT_KEY_KP0,
    TT_KEY_KP1,
    TT_KEY_KP2,
    TT_KEY_KP3,
    TT_KEY_KP4,
    TT_KEY_KP5,
    TT_KEY_KP6,
    TT_KEY_KP7,
    TT_KEY_KP8,
    TT_KEY_KP9,
    TT_KEY_KP_MINUS,
    TT_KEY_KP_COMMA,
    TT_KEY_KP_PERIOD,
    TT_KEY_KP_SLASH,
    TT_KEY_KP_ASTERISK,
    TT_KEY_KP_PLUS,
    TT_KEY_KP_ENTER,
    /**
     * DEC's four top-row keys. Always `SS3`, in every mode — they have no
     * numeric form to fall back to.
     */
    TT_KEY_PF1,
    TT_KEY_PF2,
    TT_KEY_PF3,
    TT_KEY_PF4,
    /**
     * The VT220 editing keypad. On a PC keyboard these are Insert, Delete,
     * Home, End, Page Up and Page Down.
     */
    TT_KEY_FIND,
    TT_KEY_INSERT,
    TT_KEY_REMOVE,
    TT_KEY_SELECT,
    TT_KEY_PREV,
    TT_KEY_NEXT,
    TT_KEY_F6,
    TT_KEY_F7,
    TT_KEY_F8,
    TT_KEY_F9,
    TT_KEY_F10,
    TT_KEY_F11,
    TT_KEY_F12,
    TT_KEY_F13,
    TT_KEY_F14,
    /**
     * F15 on a PC keyboard; DEC called it Help.
     */
    TT_KEY_HELP,
    /**
     * F16; DEC called it Do.
     */
    TT_KEY_DO,
    TT_KEY_F17,
    TT_KEY_F18,
    TT_KEY_F19,
    TT_KEY_F20,
    /**
     * `IdXF1`…`IdXF5` — xterm's F1-F5, which DEC's numbering does not have
     * because PF1-PF4 sat there.
     */
    TT_KEY_XF1,
    TT_KEY_XF2,
    TT_KEY_XF3,
    TT_KEY_XF4,
    TT_KEY_XF5,
    /**
     * Local commands. They have key ids because `KEYBOARD.CNF` can bind
     * them, but they put nothing on the wire.
     */
    TT_KEY_HOLD,
    TT_KEY_PRINT,
    TT_KEY_BREAK,
    /**
     * Shift+Tab.
     */
    TT_KEY_BACK_TAB,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtKey TtKey;
#else
typedef uint32_t TtKey;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * `IdMouseEvent*` — `tttypes.h:668`.
 */
enum TtMouseEvent
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Not a real event: DECRQLP asks the locator where it is.
     */
    TT_MOUSE_EVENT_CUR_STAT,
    TT_MOUSE_EVENT_PRESS,
    TT_MOUSE_EVENT_RELEASE,
    TT_MOUSE_EVENT_MOVE,
    /**
     * `button` is 0 for wheel-up and 1 for wheel-down (`vtwin.cpp:2542`
     * passes `zDelta < 0`).
     */
    TT_MOUSE_EVENT_WHEEL,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtMouseEvent TtMouseEvent;
#else
typedef uint32_t TtMouseEvent;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * `ts.Parity` — `commlib.c:182`, all five values including the two Linux
 * needs `CMSPAR` for.
 *
 * `repr(u8)` here and on the two enums below: the C ABI names these
 * variants directly rather than keeping a second copy. See `tt-ffi`.
 */
enum TtParity
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    TT_PARITY_NONE,
    TT_PARITY_ODD,
    TT_PARITY_EVEN,
    /**
     * The parity bit is always 1.
     */
    TT_PARITY_MARK,
    /**
     * The parity bit is always 0.
     */
    TT_PARITY_SPACE,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtParity TtParity;
#else
typedef uint8_t TtParity;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * `ts.Flow` — `commlib.c:204`.
 */
enum TtFlowControl
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    TT_FLOW_CONTROL_NONE,
    /**
     * `IdFlowX`. The characters are configurable; the thresholds are not,
     * on Linux.
     */
    TT_FLOW_CONTROL_XON_XOFF,
    /**
     * `IdFlowHard`, `fOutxCtsFlow`.
     */
    TT_FLOW_CONTROL_RTS_CTS,
    /**
     * `IdFlowHardDsrDtr`, `fOutxDsrFlow`. **Linux has no such termios bit**,
     * so writes are gated in userspace — see [`SerialConn::write`].
     */
    TT_FLOW_CONTROL_DSR_DTR,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtFlowControl TtFlowControl;
#else
typedef uint8_t TtFlowControl;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * `dcb.fDtrControl` / `dcb.fRtsControl`.
 */
enum TtPinControl
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * `*_CONTROL_DISABLE` — hold the line low.
     */
    TT_PIN_CONTROL_DISABLE,
    /**
     * `*_CONTROL_ENABLE` — hold it high. Most devices expect this.
     */
    TT_PIN_CONTROL_ENABLE,
    /**
     * `*_CONTROL_HANDSHAKE` — the driver raises and lowers it as its buffer
     * fills. On Linux only RTS can do this, and only as part of `CRTSCTS`.
     */
    TT_PIN_CONTROL_HANDSHAKE,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum TtPinControl TtPinControl;
#else
typedef uint8_t TtPinControl;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * An owned list of ports. Free it with [`tt_port_list_free`].
 */
typedef struct TtPortList TtPortList;

/**
 * A terminal, and optionally something for it to talk to. Opaque.
 */
typedef struct TtSession TtSession;

/**
 * A connection being set up. Free it with [`tt_ssh_connect_free`], whether or
 * not it reached [`TT_SSH_READY`].
 */
typedef struct TtSshConnect TtSshConnect;

/**
 * An owned list of strings. Free it with [`tt_string_list_free`].
 */
typedef struct TtStringList TtStringList;

/**
 * What a session is created with.
 *
 * Deliberately small. `tt_vt::Config` has thirty-odd fields and every one of
 * them is a `TERATERM.INI` key, which makes it the settings schema's job
 * (Stage 2) rather than something to hand-transcribe into a C struct now and
 * throw away later. What is here is what a window has to decide before it can
 * draw: how big the terminal is, how much history to keep, and which DEC
 * terminal to answer as.
 */
typedef struct {
    size_t cols;
    size_t rows;
    /**
     * Lines of scrollback to retain. Tera Term's `ts.ScrollBuffMax`.
     */
    size_t scrollback;
    TtTermId term_id;
    /**
     * The character cell in pixels. The core wants it for exactly two things:
     * turning a mouse position into a cell, and SGR-pixel mouse reports,
     * which do not convert at all. Zero means "not known yet" and mouse
     * reporting will be wrong until [`tt_session_set_cell_pixels`] says
     * otherwise.
     */
    int32_t cell_w;
    int32_t cell_h;
} TtConfig;

/**
 * One screen cell. POD, `repr(C)`: this crosses the C ABI unchanged.
 */
typedef struct {
    uint32_t text[TT_CELL_TEXT_MAX];
    uint32_t fg;
    uint32_t bg;
    uint32_t attrs;
    uint8_t width_class;
} TtCell;

/**
 * What a session log records and how it is written.
 *
 * Every field is a `TERATERM.INI` key, so this is one of the few places the
 * settings schema will land in Stage 2 rather than a struct to keep growing
 * by hand. It is here now because a console capture is the reason people
 * leave a serial terminal open, not a nicety.
 */
typedef struct {
    /**
     * True for a byte-for-byte capture — `ts.LogBinary`. False logs the text
     * the terminal decided to display, with escape sequences already
     * consumed by the parser.
     *
     * **A raw log is silently untimestamped.** That is upstream's behaviour
     * and the right one: a `[time] ` in the middle of a byte capture makes it
     * no longer replayable.
     */
    bool raw;
    TtLogTimestamp timestamp;
    /**
     * Add to an existing file rather than truncating it.
     */
    bool append;
    /**
     * Rotate past this many bytes. Zero disables rotation, as does
     * `rotate_keep` of zero.
     */
    uint64_t rotate_size;
    /**
     * Generations to keep: `file.1` is the newest, `file.<n>` the oldest.
     */
    uint32_t rotate_keep;
    /**
     * Write CR LF for each line rather than LF. Upstream always does;
     * this defaults to off, because the artefact is a text file read on
     * Linux.
     */
    bool crlf;
} TtLogOptions;

/**
 * The return of every fallible call. Zero is success and negative is
 * failure; the codes exist so a frontend can branch without parsing English,
 * and [`tt_last_error`] carries the sentence for the user.
 */
typedef int32_t TtStatus;

/**
 * Where the cursor is and whether to draw it.
 */
typedef struct {
    size_t x;
    /**
     * The row on the **live screen**, which is not where to paint it once the
     * view has scrolled back — [`tt_session_cursor_view_row`] is.
     */
    size_t y;
    /**
     * DECTCEM. A hidden cursor is still *somewhere*, so the position stays
     * meaningful — `x`/`y` are not zeroed when this is false.
     */
    bool visible;
    /**
     * Tera Term's `Wrap`: the last glyph landed on the right margin and the
     * *next* one wraps. Worth having because it explains a cursor that looks
     * stuck on the last column.
     */
    bool pending_wrap;
} TtCursor;

/**
 * One setting, as data — the row a generated dialog builds a widget from.
 *
 * **This is the point of having a schema at all.** `PLAN.md` puts ~13.8k
 * lines of dialog code over Tera Term's 909-line settings struct, across 76
 * dialog templates; a dialog that reads this table has nothing to keep in
 * step with it, while one generated as C++ would be a second copy of the list
 * living in the other build system.
 *
 * Every string is `NUL`-terminated, never null except `label`, and **lives
 * for the life of the process**: they describe the schema rather than any
 * session's values, so unlike everything else in this header they need no
 * "valid until" rule.
 */
typedef struct {
    /**
     * The dotted name a script and [`tt_session_setting`] use.
     */
    const char *name;
    /**
     * Everything before the first dot: which page of the dialog it belongs on.
     */
    const char *page;
    /**
     * Its `TERATERM.INI` section and key. Two settings may share a key —
     * `TerminalSize` holds both `terminal.cols` and `terminal.rows`.
     */
    const char *section;
    const char *key;
    /**
     * The default, in the INI's own spelling. For a `Bool` this is
     * load-bearing rather than cosmetic: `GetOnOff` is default-biased
     * (`ttset.c:344`), so with a default of `on` anything but `off` reads as
     * on, and with a default of `off` only `on` does. `Key=1` therefore means
     * opposite things for two settings out of the same file.
     */
    const char *default_value;
    /**
     * The `.lng` key for the label, or **null** where upstream has no dialog
     * for this setting. Those are real settings people set by hand; they have
     * no widget yet, not no meaning.
     */
    const char *label;
    /**
     * The schema's own comment, which is where the citation for the default
     * lives. Meant for a tooltip and for the generated documentation.
     */
    const char *doc;
    TtSettingKind kind;
    /**
     * Bounds, for `TT_SETTING_KIND_INT_RANGE`. Note what the file does
     * outside them, because a spin box cannot express it: at or below `min`
     * takes the *default*, above `max` takes `max` (`ttset.c:615`).
     */
    int32_t min;
    int32_t max;
    /**
     * How many spellings an `Enum` accepts; zero for every other kind.
     */
    size_t choices;
} TtSettingField;

typedef struct {
    TtEventKind kind;
    /**
     * Meaningful for [`TtEventKind::BadByte`] only.
     */
    uint8_t byte;
    /**
     * Meaningful for [`TtEventKind::Resize`] only.
     */
    uint16_t cols;
    uint16_t rows;
    /**
     * Meaningful for [`TtEventKind::Title`] and [`TtEventKind::LogFailed`];
     * null otherwise.
     */
    const char *text;
} TtEvent;

/**
 * How to run a transfer.
 *
 * One struct rather than a function per protocol, because a frontend builds
 * it from a dialog: the user picks a protocol and the options that belong to
 * it, and the fields that do not apply are ignored. Which those are is in
 * `tt-xfer`'s `Job` — XMODEM has a text flag and no filename on the wire,
 * Kermit has four modes and no direction, Raw has neither.
 */
typedef struct {
    TtXferProtocol protocol;
    /**
     * Ignored by Kermit, which takes `kermit_mode` instead, and by Raw.
     */
    bool sending;
    /**
     * XMODEM: 1 = checksum, 2 = CRC, 3 = 1K CRC, 4 = 1K checksum.
     * YMODEM: 1 = 1K, 2 = G, 3 = single. Zero takes the sensible default,
     * which for YMODEM is the *only* value its packet builder handles.
     */
    int32_t option;
    /**
     * XMODEM only: CRLF translation and `^Z` padding.
     */
    bool text;
    /**
     * ZMODEM only, and on by default. Clearing it asks for end-of-line
     * translation, which is almost never wanted.
     */
    bool binary;
    /**
     * ZMODEM and B-Plus: the peer's trigger has already gone past in the
     * terminal stream, so the protocol pushes it back and reads it itself.
     */
    bool auto_start;
    /**
     * Kermit only: 1 = receive, 2 = get, 3 = send, 4 = finish.
     */
    int32_t kermit_mode;
    /**
     * Raw only: stop after this many seconds of silence.
     */
    int32_t autostop_sec;
} TtXferJob;

/**
 * Where a running transfer has got to.
 *
 * **Every number here is something the protocol reported, and the protocols
 * throttle themselves to ten updates a second** (`zmodem.c:197`). A transfer
 * that finishes in under a tenth of a second finishes having reported
 * nothing, so a frontend must not read `bytes == 0` as "not started".
 */
typedef struct {
    /**
     * "ZMODEM", "Kermit" — the protocol's own word for itself. Borrowed and
     * valid until the next call to this function on this session.
     */
    const char *protocol;
    /**
     * The file in flight, as the protocol named it. Empty before the first
     * one is opened.
     */
    const char *file;
    bool sending;
    int64_t bytes;
    int64_t packets;
    /**
     * Position within the current file, and its size. `total` is 0 when the
     * size is not known — XMODEM never learns it.
     */
    int64_t done;
    int64_t total;
    /**
     * The whole-percent high-water mark, or -1 when there is no meaningful
     * bar to draw.
     */
    int32_t percent;
    uint32_t elapsed_ms;
} TtTransferStatus;

/**
 * How the last transfer ended.
 */
typedef struct {
    bool success;
    bool cancelled;
    /**
     * What the protocol said when it failed — "Cannot create file" — or null.
     * Often the only account of the failure there is. Borrowed, and valid
     * until the next call to this function on this session.
     */
    const char *message;
    int64_t bytes;
    uint32_t elapsed_ms;
} TtTransferResult;

/**
 * What `ShiftKey()`/`AltKey()`/`ControlKey()` would have answered.
 */
typedef struct {
    bool shift;
    bool alt;
    bool ctrl;
} TtModifiers;

/**
 * The serial line settings, one field per `commlib.c` DCB field that Tera
 * Term actually sets.
 */
typedef struct {
    uint32_t baud;
    /**
     * 5 to 8. **Five and six are usually a lie**: an FTDI refuses `CS6` and
     * *accepts* `CS5` while still putting eight bits on the wire, so
     * [`tt_session_connect_serial`] reads the setting back and fails with
     * [`TT_ERR_UNSUPPORTED`] rather than let a dialog claim five.
     */
    uint8_t data_bits;
    TtParity parity;
    /**
     * 1 or 2.
     */
    uint8_t stop_bits;
    TtFlowControl flow;
    /**
     * The XON/XOFF pair. Tera Term hardcodes the standard characters in
     * `CommResetSerial` but `TTTSet` carries them, so they are settable.
     */
    uint8_t xon;
    uint8_t xoff;
    TtPinControl dtr;
    TtPinControl rts;
    /**
     * Escape the input so a line break arrives as a
     * [`TtEventKind::Break`] instead of a `0x00`. Without it the two are the
     * same byte and there is no way to tell them apart.
     */
    bool detect_break;
    /**
     * How long a read waits before returning empty — short enough that a
     * disconnect is noticed promptly, long enough not to spin.
     */
    uint32_t read_timeout_ms;
} TtSerialParams;

/**
 * How much of the telnet protocol to speak.
 */
typedef uint32_t TtTelnetMode;

/**
 * What to tell the far end about this terminal.
 */
typedef struct {
    /**
     * [`TT_TELNET_RAW`], [`TT_TELNET_AUTO`] or [`TT_TELNET_NEGOTIATE`].
     *
     * [`tt_telnet_params_default`] sets it from the port, which is upstream's
     * rule: negotiate on 23, auto-detect elsewhere. **Do not "improve" that
     * to always negotiating** — a terminal server is not a telnet server, and
     * opening at one with `WILL TERMINAL-TYPE` puts five bytes of protocol
     * into somebody's serial console.
     */
    TtTelnetMode mode;
    /**
     * `$TERM` for `TERMINAL-TYPE`. Null means `xterm-256color`.
     */
    const char *term_type;
    /**
     * `TERMINAL-SPEED`, which is a claim about the line behind the server
     * rather than about this connection. Upstream defaults both to 38400.
     */
    uint32_t input_speed;
    uint32_t output_speed;
    /**
     * Ask for `BINARY` in the opening burst. Upstream's `ts.TelBin`, which
     * defaults **off** — it agrees if asked, but does not ask.
     */
    bool binary;
    uint32_t connect_timeout_ms;
} TtTelnetParams;

/**
 * What to run on a local pty, and what to tell it about itself.
 */
typedef struct {
    /**
     * The command and its arguments, `argv[0]` first. **Null or empty means
     * the user's login shell**, which is what a "Local shell" menu item
     * wants; anything else is run as itself.
     */
    const char *const *argv;
    size_t argc;
    /**
     * Working directory. Null means the user's home, which is where a window
     * opened from a desktop menu should start.
     */
    const char *cwd;
    /**
     * `$TERM`. Null means `xterm-256color`.
     *
     * Set by us and **never inherited**: a window launched from another
     * terminal would otherwise hand the shell that terminal's name, and one
     * launched from a desktop menu would hand it nothing at all.
     */
    const char *term;
    /**
     * Start the shell as a login shell, so `~/.profile` runs. Upstream's
     * default too — `cygterm.cfg`'s `LOGIN_SHELL = Yes`.
     *
     * **Only meaningful when `argv` is empty**: the trick is a `-bash` in
     * `argv[0]`, and `argv[0]` is also what gets looked up on `PATH`.
     */
    bool login_shell;
} TtPtyParams;

/**
 * One serial port, as a picker wants to show it. Every string is borrowed
 * from the owning [`TtPortList`] and dies with it.
 */
typedef struct {
    /**
     * The kernel device node — `/dev/ttyUSB0`. Fine to show; wrong to store.
     */
    const char *device;
    /**
     * **What to pass to [`tt_session_connect_serial`], and what to save in a
     * session profile.** `/dev/ttyUSB<n>` is assigned in attach order, so
     * unplugging two adapters and replugging them the other way round swaps
     * their names; this is the `by-path` name where there is one, which
     * encodes the USB topology and holds still.
     */
    const char *open_path;
    /**
     * The `by-path` name on its own, or null when the bus has none.
     */
    const char *stable_id;
    /**
     * One line for a picker — device plus product name.
     */
    const char *label;
    /**
     * Whether the USB fields below mean anything.
     */
    bool has_usb;
    uint16_t vid;
    uint16_t pid;
    /**
     * Any of these may be null. `serial` in particular is often absent on
     * multi-port adapters, which is why it is not the identity.
     */
    const char *manufacturer;
    const char *product;
    const char *serial;
} TtPortInfo;

/**
 * What to do about a host key the `known_hosts` files do not already trust.
 *
 * `TT_HOST_KEY_POLICY_ASK` is what a GUI wants; the other three exist because
 * `~/.ssh/config` contains them and a client that ignores `StrictHostKeyChecking`
 * is a client the user has to configure twice.
 */
typedef uint32_t TtHostKeyPolicy;

/**
 * Where to connect and what to try.
 *
 * Every string may be null, and null does not mean "empty" — it means "take
 * it from `~/.ssh/config`, or from the default". That distinction is the
 * whole value of `use_ssh_config`: a dialog that leaves the user field blank
 * must get the config's `User`, not an empty user name.
 */
typedef struct {
    /**
     * The host, or an alias from `~/.ssh/config`. Required.
     */
    const char *host;
    /**
     * 0 means the config's `Port`, or 22.
     */
    uint16_t port;
    /**
     * Null means the config's `User`, or `$USER`.
     */
    const char *user;
    /**
     * `$TERM` for the far end. Null means `xterm-256color`, which is what
     * the engine actually implements.
     */
    const char *term;
    /**
     * Read `~/.ssh/config` and fill in everything this struct leaves unset —
     * the user, the port, the identity files, `StrictHostKeyChecking`, and
     * whether the config already says this is old equipment.
     */
    bool use_ssh_config;
    /**
     * A null-terminated array of key paths, or null for the OpenSSH defaults
     * (or whatever the config named).
     */
    const char *const *identities;
    /**
     * A null-terminated array of `known_hosts` files, or null for the
     * config's `UserKnownHostsFile` and then `~/.ssh/known_hosts`.
     *
     * Present because Tera Term keeps its own `ssh_known_hosts`, and the
     * migration path in `PLAN.md` is to read *both*. New keys are recorded
     * in the first.
     */
    const char *const *known_hosts;
    bool use_agent;
    /**
     * Offer the pre-2020 algorithms as well. A config naming SHA-1 key
     * exchange or a CBC cipher turns this on by itself.
     */
    bool legacy;
    uint32_t connect_timeout_ms;
    /**
     * 0 for none, which is OpenSSH's default.
     */
    uint32_t keepalive_ms;
    TtHostKeyPolicy host_key_policy;
} TtSshParams;

/**
 * What [`tt_ssh_connect_poll`] found.
 */
typedef int32_t TtSshStep;

/**
 * What the `known_hosts` files made of the key the server presented.
 */
typedef uint32_t TtHostKeyVerdict;

/**
 * The far end's host key, and what the files said about it.
 *
 * Every pointer is borrowed from the [`TtSshConnect`] and is valid until the
 * next [`tt_ssh_connect_poll`] on it.
 */
typedef struct {
    const char *host;
    uint16_t port;
    /**
     * The key's own type name as `known_hosts` records it — `ssh-ed25519`,
     * `ssh-rsa` — not the negotiated signature algorithm.
     */
    const char *algorithm;
    /**
     * `SHA256:…`, the form every other client prints.
     */
    const char *fingerprint;
    TtHostKeyVerdict verdict;
    /**
     * For [`TT_HOST_KEY_CHANGED`]: `path:line` of the entry that disagrees,
     * so the message can tell the user what to delete. Null otherwise.
     */
    const char *recorded_at;
    /**
     * For [`TT_HOST_KEY_CHANGED`]: the fingerprint on file, for showing
     * beside the new one. Null otherwise.
     */
    const char *recorded_fingerprint;
    /**
     * For [`TT_HOST_KEY_NEW_ALGORITHM`]: the algorithms already recorded,
     * comma-separated. Null otherwise.
     */
    const char *also_known;
} TtSshHostKeyPrompt;

/**
 * What is being asked for.
 */
typedef uint32_t TtSshAuthKind;

/**
 * One line of something to type.
 */
typedef struct {
    const char *text;
    /**
     * Whether to show what is typed. The server chooses.
     */
    bool echo;
} TtSshPrompt;

/**
 * A question that has to reach the user before authentication can go on.
 *
 * Borrowed like [`TtSshHostKeyPrompt`], and valid for exactly as long.
 */
typedef struct {
    TtSshAuthKind kind;
    /**
     * The server's own wording, where it sent any. Never null; often empty.
     */
    const char *name;
    const char *instruction;
    /**
     * For [`TT_SSH_AUTH_PASSPHRASE`]: the key file. Null otherwise.
     */
    const char *path;
    const TtSshPrompt *prompts;
    size_t prompt_count;
} TtSshAuthPrompt;

#define TT_OK 0

/**
 * A null pointer, a length that overflows, text that is not UTF-8, or a
 * parameter outside its range. Always a bug on the calling side.
 */
#define TT_ERR_INVALID -1

/**
 * The far end is gone. When a pump or a write says this, the session has
 * already dropped the connection and queued a
 * [`TtEventKind::Disconnected`].
 *
 * **An open of a path that does not exist reports this too**, rather than
 * some "no such port". That is `tt_conn`'s call and it is the right one: the
 * case is a saved profile naming an adapter that has since been unplugged,
 * and "not found" sends the user hunting for a typo instead of for the
 * cable.
 */
#define TT_ERR_DISCONNECTED -2

/**
 * The port exists but something else holds it — `minicom` in another window,
 * a ModemManager probe. By far the most common serial failure, and the one
 * where the wrong message wastes the most of the user's time.
 */
#define TT_ERR_BUSY -3

/**
 * The port exists and we are not allowed to open it. On Linux, usually not
 * being in `dialout`.
 */
#define TT_ERR_PERMISSION -4

/**
 * A setting this platform cannot express, or that the driver accepted and
 * then ignored — five data bits on an FTDI, for one.
 */
#define TT_ERR_UNSUPPORTED -5

/**
 * Anything else the operating system said.
 */
#define TT_ERR_IO -6

/**
 * The SSH protocol failed — the socket, the banner, key exchange, opening
 * the channel.
 */
#define TT_ERR_SSH -7

/**
 * The far end is not who `known_hosts` says it is, or is who it says must be
 * refused. **Separate from [`TT_ERR_SSH`] because a frontend must not offer
 * to retry**: this is the one failure where the right affordance is none.
 */
#define TT_ERR_HOST_KEY -8

/**
 * Every authentication method failed or was not on offer. [`tt_last_error`]
 * names what the server said it would still accept, which is the only thing
 * that makes the message actionable.
 */
#define TT_ERR_AUTH -9

/**
 * Every byte is data, `0xFF` included. What a console server's per-line port
 * needs, and the only mode that cannot corrupt a binary stream.
 */
#define TT_TELNET_RAW 0

/**
 * Data until the first `IAC` arrives, and telnet from then on. Upstream's
 * `TelAutoDetect`, which defaults on.
 */
#define TT_TELNET_AUTO 1

/**
 * Telnet from the first byte, opening with the negotiation upstream opens
 * with. Upstream does this only when the port is 23.
 */
#define TT_TELNET_NEGOTIATE 2

#define TT_HOST_KEY_POLICY_ASK 0

/**
 * `accept-new`: record a first-seen host silently, refuse a changed one.
 */
#define TT_HOST_KEY_POLICY_ACCEPT_NEW 1

/**
 * `yes`: refuse anything not recorded, and never prompt.
 */
#define TT_HOST_KEY_POLICY_STRICT 2

/**
 * `no`: connect to anything.
 */
#define TT_HOST_KEY_POLICY_ACCEPT_ANY 3

/**
 * Nothing anywhere mentions this host. A first connection.
 */
#define TT_HOST_KEY_UNKNOWN 0

/**
 * Recorded under this algorithm, and **different**. The alarming one — a
 * frontend should not present it with the same words as the others.
 */
#define TT_HOST_KEY_CHANGED 1

/**
 * The host is recorded, but only under other key algorithms. Usually a
 * server that gained an Ed25519 key.
 */
#define TT_HOST_KEY_NEW_ALGORITHM 2

#define TT_SSH_AUTH_PASSWORD 0

#define TT_SSH_AUTH_KEYBOARD_INTERACTIVE 1

/**
 * The passphrase for a local private key. `path` says which file, and it is
 * the only prompt that is ours rather than the server's.
 */
#define TT_SSH_AUTH_PASSPHRASE 2

/**
 * Nothing yet. Wait for the descriptor to become readable.
 */
#define TT_SSH_WORKING 0

/**
 * [`tt_ssh_connect_host_key`] has a question. Answer it with
 * [`tt_ssh_connect_answer_host_key`].
 */
#define TT_SSH_HOST_KEY 1

/**
 * [`tt_ssh_connect_auth`] has a question. Answer it with
 * [`tt_ssh_connect_answer_auth`].
 */
#define TT_SSH_AUTH 2

/**
 * Connected, and attached to the session that was passed in. The handle has
 * nothing more to say and can be freed.
 */
#define TT_SSH_READY 3

/**
 * Over. [`tt_last_error`] says why.
 */
#define TT_SSH_FAILED 4

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Why the last call on **this thread** failed.
 *
 * Never null and never stale-dangling: it points at a thread-local buffer
 * that lives as long as the thread, and is overwritten by the next failing
 * call on it. Copy it if you intend to keep it. The contents are unspecified
 * when nothing has failed yet — check the status, not the string.
 */
const char *tt_last_error(void);

/**
 * The core's version, for an about box and for a shell checking it did not
 * pick up a stale library.
 */
const char *tt_version(void);

/**
 * Fill `out` with the defaults — 80x24, 10000 lines of scrollback, VT100.
 */
void tt_config_default(TtConfig *out);

/**
 * Create a session. Returns null only if `config` is null.
 *
 * The terminal exists immediately and can be fed and drawn with nothing
 * connected, which is what makes a local echo test and a replayed session log
 * work.
 */
TtSession *tt_session_new(const TtConfig *config);

/**
 * Destroy a session, closing its connection. Null is a no-op.
 */
void tt_session_free(TtSession *session);

/**
 * How long a write may block before it returns short. 200 ms by default; a
 * frontend pumping from its UI thread wants it well under a frame.
 */
void tt_session_set_write_timeout(TtSession *session, uint32_t ms);

size_t tt_session_cols(const TtSession *session);

size_t tt_session_rows(const TtSession *session);

/**
 * One row of what the window is **showing**, borrowed straight out of the
 * grid — no copy and no allocation, which is the point of a POD [`Cell`].
 *
 * `y` runs over the viewport, not over the grid. With
 * [`tt_session_view_offset`] at zero — which it is until something scrolls
 * back — the two are the same thing and this is the live screen. Otherwise
 * row 0 is that many lines up in the scrollback.
 *
 * `out_len` receives the row's length, which is always
 * [`tt_session_cols`], history included. Null on an out-of-range `y`.
 *
 * **Valid until the next call that can change the grid** — a pump, a feed, a
 * resize, a scroll, or anything that sends. In practice: read every row you
 * are about to paint, paint, then pump.
 */
const TtCell *tt_session_row(const TtSession *session,
                             size_t y,
                             size_t *out_len);

/**
 * Fill `out` with the defaults: text, no timestamp, truncate, no rotation.
 */
void tt_log_options_default(TtLogOptions *out);

/**
 * Start writing a session log to `path`, replacing any log already open.
 *
 * Nothing is logged retroactively — the capture starts here. (Upstream can
 * prepend the scrollback; the function it uses to do that is one of the
 * upstream bugs on file, since it truncates every line at its first wide
 * character, so that option waits for the report to be answered.)
 */
TtStatus tt_session_log_start(TtSession *session,
                              const char *path,
                              const TtLogOptions *options);

/**
 * Close the log, flushing it. A no-op when none is open.
 */
void tt_session_log_stop(TtSession *session);

/**
 * The path being logged to, or null when nothing is.
 *
 * Borrowed, and valid until the next call to this function on this session.
 */
const char *tt_session_log_path(TtSession *session);

/**
 * Bytes written to the log since it was opened, across all generations.
 */
uint64_t tt_session_log_bytes(const TtSession *session);

/**
 * How many lines of history there are to scroll through.
 */
size_t tt_session_scrollback_len(const TtSession *session);

/**
 * How far back the view is, in lines. Zero is the live screen.
 *
 * **Read it again after every pump.** It is not a value the frontend owns:
 * the core moves it so that a scrolled-back view stays on the same *lines*
 * while the host keeps printing. A scrollbar that assumed its own last write
 * was still current would fight the terminal for the thumb.
 */
size_t tt_session_view_offset(const TtSession *session);

/**
 * Scroll the view back by `offset` lines, or to the live screen with zero.
 *
 * Clamped to the history that exists, so `SIZE_MAX` means "as far back as it
 * goes" and needs no separate call.
 */
void tt_session_set_view_offset(TtSession *session, size_t offset);

/**
 * Which viewport row the cursor is on, or false when it is not in view.
 *
 * The cursor belongs to the live screen, so scrolling back moves it *down*
 * and eventually off the bottom. A painter that used [`TtCursor::y`] directly
 * would draw a cursor onto a line of history it has nothing to do with.
 */
bool tt_session_cursor_view_row(const TtSession *session, size_t *out);

/**
 * The absolute number of the line shown at viewport row `y`.
 *
 * A viewport row says *where* a line is, and that changes every time the host
 * prints. This says *which* line it is, and that never changes — which is what
 * a frontend needs to hold on to one across output. A selection is the thing
 * that needs it: highlighting rows 3 to 5 means a highlight that walks up the
 * screen as the device talks, and a copy that takes whatever slid underneath.
 *
 * The numbering starts at zero on the first line the terminal ever showed and
 * counts every line that has scrolled off since, so the top of the live page
 * is always [`tt_session_top_line`]. `y` is not range-checked: a row past the
 * bottom of the page names a line that has not been printed yet, which
 * [`tt_session_line`] then reports as absent.
 */
uint64_t tt_session_line_at(const TtSession *session,
                            size_t y);

/**
 * The absolute number of the line at the top of the **live** page.
 *
 * Equivalently: how many lines have ever scrolled off it. The difference
 * between two readings is how far the content moved.
 */
uint64_t tt_session_top_line(const TtSession *session);

/**
 * One line by absolute number — the scrollback and the page alike, and
 * **without regard to what is currently in view**.
 *
 * [`tt_session_row`] is the painter's call and this is the one for anything
 * that outlived a scroll. Null when the line has been evicted from the
 * scrollback or has not been printed yet, which a caller holding an old number
 * has to be able to ask about rather than range-check first. Sets no error:
 * asking about a line that has aged out is ordinary.
 *
 * Borrowed on the same terms as [`tt_session_row`] — valid until the next call
 * that can change the grid.
 */
const TtCell *tt_session_line(const TtSession *session,
                              uint64_t line,
                              size_t *out_len);

void tt_session_cursor(const TtSession *session, TtCursor *out);

/**
 * The window title, from OSC 0 / OSC 2. Never null; empty before the host
 * sets one.
 *
 * Borrowed, and **valid until the next call to this function** on this
 * session. The [`TtEventKind::Title`] event carries the same string and is
 * the cheaper way to notice a change.
 */
const char *tt_session_title(TtSession *session);

/**
 * DECSCNM. The grid does not apply it — swapping every cell's colours is the
 * renderer's job, and doing it in the buffer would corrupt what a copy or a
 * session log sees.
 */
bool tt_session_reverse_video(const TtSession *session);

/**
 * Whether the Backspace key should send `BS` (0x08) rather than `DEL`
 * (0x7F) — `ts.BSKey`, which `DECSET 67` (DECBKM) sets and resets.
 *
 * One of the two keys a frontend has to encode itself, because upstream
 * handles them in `KeyDown` rather than in the key table and so they are not
 * [`Key`]s. The other is Return, which needs nothing: send `"\r"` through
 * [`tt_session_send_text`] and LNM is applied there.
 *
 * Getting this backwards is not cosmetic. A host expecting DEL and receiving
 * BS erases nothing and the line editor beeps, which reads as a broken
 * keyboard rather than as a mode.
 */
bool tt_session_backspace_sends_bs(const TtSession *session);

/**
 * Whether the frontend should be tracking the mouse at all, and therefore
 * whether a drag belongs to the host or to text selection.
 */
TtTracking tt_session_mouse_tracking(const TtSession *session);

/**
 * A palette entry, for the painter. False for `index > 255`.
 *
 * Tera Term stores one byte of colour per cell, so this is the *whole* colour
 * story — `SGR 38;2;r;g;b` has already resolved to the nearest index by the
 * time a cell holds it. Entries 0-15 are the VGA values, not xterm's.
 *
 * Note what the cell says: `fg`/`bg` mean a palette index only when
 * `TT_ATTR2_FORE` / `TT_ATTR2_BACK` is set in `attrs`. Without the bit the
 * cell is asking for the terminal's *configured* default text colour, which
 * is the frontend's to choose — painting index 0 there gives a black-on-black
 * screen.
 */
bool tt_palette_rgb(uint32_t index,
                    uint8_t *r,
                    uint8_t *g,
                    uint8_t *b);

/**
 * How many settings there are. The index runs `0..count` and is stable for
 * the life of the process, but **not across versions** — the schema grows.
 */
size_t tt_settings_field_count(void);

/**
 * Describe setting `index`. False, and `out` untouched, past the end.
 */
bool tt_settings_field(size_t index, TtSettingField *out);

/**
 * The `n`th spelling an `Enum` setting accepts, or null.
 *
 * These are the INI's own spellings, which is what
 * [`tt_session_set_setting`] takes and [`tt_session_setting`] returns — so a
 * combo box can be built out of them and read back without a table of its
 * own. They are not translated; the `.lng` label belongs to the setting, not
 * to its values.
 */
const char *tt_settings_choice(size_t index,
                               size_t n);

/**
 * One setting's current value, in the INI's own spelling. Null for a name
 * that is not in the schema.
 *
 * Borrowed, and valid until the next call to this function on this session.
 */
const char *tt_session_setting(TtSession *session, const char *name);

/**
 * Set one setting by name and apply it to the running terminal.
 *
 * The value is parsed exactly as the file would parse it — bounds, quote
 * stripping, and `GetOnOff`'s default-biased booleans included — so a dialog,
 * a script and a hand-edited `TERATERM.INI` cannot disagree about what a
 * value means. An out-of-range number is therefore **not** an error; it lands
 * where the file would put it.
 *
 * `TT_ERR_INVALID` for a name that is not in the schema. Applying can also
 * resize the terminal, which is told to the far end and can fail there.
 *
 * **It overwrites modes the host set**, and that is upstream's behaviour
 * rather than an oversight: in Tera Term the setting and the mode are the
 * same variable, so `DECSET 67` writes `ts.BSKey` and the settings dialog
 * writes it back.
 */
TtStatus tt_session_set_setting(TtSession *session,
                                const char *name,
                                const char *value);

/**
 * Read `TERATERM.INI` and apply all of it.
 *
 * A file that does not exist reads as an empty one — every setting takes its
 * default — because that is a first run, not a failure.
 */
TtStatus tt_session_settings_load(TtSession *session,
                                  const char *path);

/**
 * Write every setting back, leaving the rest of the file alone.
 *
 * The file is re-read first and only the keys the schema owns are touched, so
 * comments, ordering, spelling and every setting this project does not know
 * about survive — which is what makes a `TERATERM.INI` shared with a real
 * Tera Term keep working.
 */
TtStatus tt_session_settings_save(const TtSession *session, const char *path);

/**
 * Take everything that has happened since the last drain.
 *
 * `*out` receives the array and the return is its length; `*out` is null when
 * the length is zero. **Both the array and every `text` in it are borrowed
 * and valid until the next drain on this session.**
 *
 * Drained rather than delivered by callback: a callback would have to be
 * `Send` and would fire on whichever thread the pump happens to be on, which
 * is exactly what a UI toolkit cannot take.
 */
size_t tt_session_drain_events(TtSession *session, const TtEvent **out);

/**
 * Start sending files. `paths` is `count` UTF-8 paths.
 *
 * **The terminal goes deaf and mute for the duration**: keystrokes are
 * dropped and the protocol's traffic never reaches the parser, which is what
 * upstream's modal transfer dialog achieves by other means. One transfer at a
 * time per session.
 */
TtStatus tt_session_send_files(TtSession *session,
                               const TtXferJob *job,
                               const char *const *paths,
                               size_t count);

/**
 * Start receiving into `dir`.
 *
 * `name` is XMODEM's alone and may be null for everything else: XMODEM's wire
 * format carries no filename, so there is nothing to derive a destination
 * from. Supplying one to a protocol that *does* carry a name would override
 * the peer's, so it is ignored there — which is what upstream's receive
 * dialog does with the same field.
 */
TtStatus tt_session_receive_files(TtSession *session,
                                  const TtXferJob *job,
                                  const char *dir,
                                  const char *name);

/**
 * Whether a transfer is running, and where it has got to. False when none is.
 */
bool tt_session_transfer_status(TtSession *session, TtTransferStatus *out);

/**
 * How the last transfer ended. False when none has.
 *
 * Read it on [`TtEventKind::TransferDone`]: it is kept until the next
 * transfer finishes and then replaced.
 */
bool tt_session_transfer_result(TtSession *session, TtTransferResult *out);

/**
 * Ask the running transfer to stop. A no-op when none is.
 *
 * It does not stop here. The protocol sends its cancel sequence and finishes
 * on its own terms — ZMODEM arms a 500 ms timer and ends on that — so keep
 * pumping and wait for [`TtEventKind::TransferDone`].
 */
void tt_session_cancel_transfer(TtSession *session);

/**
 * Milliseconds until the running transfer needs attention, or -1 when
 * nothing is armed and -2 when no transfer is running.
 *
 * **A frontend that only wakes on [`tt_session_poll_fd`] will stall a
 * transfer.** The protocols retry by timeout — an XMODEM receiver that hears
 * nothing re-sends its `NAK` after ten seconds — and a quiet line produces no
 * descriptor wakeup at all, so nothing would ever fire it. Arm a timer for
 * this value, and re-read it after every pump.
 */
int64_t tt_session_transfer_deadline_ms(const TtSession *session);

/**
 * Move bytes in both directions for at most `budget_ms`, and write how many
 * arrived to `out_bytes` (which may be null).
 *
 * Reading is bounded by the transport's own timeout, so the budget is a
 * ceiling on the call rather than a sleep: a quiet line returns promptly with
 * zero bytes and no events, which is the normal state of a serial console and
 * has to stay cheap.
 */
TtStatus tt_session_pump(TtSession *session,
                         uint32_t budget_ms,
                         size_t *out_bytes);

/**
 * How many bytes are still waiting for the far end.
 *
 * Non-zero means flow control held the line — CTS low, an XOFF, a DSR that
 * dropped — and a short write left the rest queued for the next
 * [`tt_session_pump`].
 *
 * **A frontend that waits on [`tt_session_poll_fd`] has to watch this**, or it
 * will appear to drop keystrokes. That descriptor wakes on bytes *arriving*,
 * and a device asserting backpressure is usually not sending any, so the pump
 * that would flush the queue never happens. Run a short retry timer while
 * this is non-zero and stop it when it reaches zero; the idle case then still
 * costs nothing.
 */
size_t tt_session_pending_out(const TtSession *session);

/**
 * A descriptor that becomes readable when [`tt_session_pump`] has something
 * to do — `-1` when there is none.
 *
 * Hand it to whatever the frontend already waits on: `QSocketNotifier`,
 * `poll(2)`, `epoll`, a `GSource`. When it fires, call `tt_session_pump` with
 * a budget of **0**, which reads exactly once and returns.
 *
 * This exists because the two obvious event loops are both wrong. Pumping
 * from the UI thread blocks for the transport's read timeout every time the
 * line is quiet, which on a serial console is nearly always, and the window
 * stops repainting for that long. Pumping on a timer instead trades the
 * freeze for a wakeup every frame, forever, to discover that nothing arrived
 * — on a terminal whose whole claim is being light.
 *
 * Three things to get right:
 *
 * - **Re-read it after every connect and disconnect**, including the implicit
 *   disconnect a [`TtEventKind::Disconnected`] event reports. It belongs to
 *   the transport, not to the session.
 * - **Readable does not promise bytes.** A pump may still report zero — the
 *   break decoder can be holding a partial `PARMRK` escape. It is a wakeup,
 *   not a guarantee, and a frontend that repaints only on a `Damage` event is
 *   already doing the right thing.
 * - **Do not close it, and do not keep it past a disconnect.** It is the
 *   transport's own descriptor, not a copy.
 *
 * Returns `-1` on Windows, where a serial port is a `HANDLE` and an
 * `OVERLAPPED` event rather than a descriptor. A frontend that gets `-1` has
 * to fall back to a timer, which is what that platform will need until this
 * grows a second spelling.
 */
int tt_session_poll_fd(const TtSession *session);

/**
 * Send a key, encoded by the core because which form it takes is terminal
 * state the frontend never sees — and because `KEYBOARD.CNF` compatibility
 * means the table has to be upstream's, not one a frontend invented.
 *
 * `out_sent` (may be null) receives whether anything reached the wire: Hold,
 * Print and Break have key ids so a config can bind them and put nothing on
 * the wire.
 *
 * Ordinary printable characters do **not** come through here — use
 * [`tt_session_send_text`].
 */
TtStatus tt_session_send_key(TtSession *session, TtKey key, bool *out_sent);

/**
 * Send typed text. UTF-8; `len` may be `SIZE_MAX` for NUL-terminated.
 */
TtStatus tt_session_send_text(TtSession *session,
                              const char *text,
                              size_t len);

/**
 * Paste, bracketed when the host asked for it (`DECSET 2004`).
 *
 * Separate from [`tt_session_send_text`] because the brackets are the whole
 * point: without them a shell runs every newline in the pasted text as a
 * command, which is a well-known way to lose data to a copied trailing
 * newline.
 */
TtStatus tt_session_paste(TtSession *session, const char *text, size_t len);

/**
 * Report a mouse event, in **window pixels** rather than cells.
 *
 * Pixels because that is what upstream's `MouseReport` takes and because
 * `DECSET 1016` reports them back unconverted, so a cell-only API could not
 * express it. The core converts using the cell size it was told.
 *
 * `out_consumed` (may be null) receives whether the terminal used the event.
 * If it did not, the click is the frontend's, for selection.
 */
TtStatus tt_session_mouse(TtSession *session,
                          TtMouseEvent event,
                          uint8_t button,
                          int32_t px,
                          int32_t py,
                          TtModifiers mods,
                          bool *out_consumed);

/**
 * Focus gained or lost. Silent unless the host asked for it
 * (`DECSET 1004`), so it is safe to call on every focus change.
 */
TtStatus tt_session_focus(TtSession *session, bool focused);

/**
 * Resize the terminal **and** tell the far end.
 *
 * Both halves, in one call, because they are easy to separate by accident: a
 * grid that resized without a `TIOCSWINSZ` leaves `vi` drawing to the old
 * size, and the symptom looks like a redraw bug rather than a missing ioctl.
 */
TtStatus tt_session_resize(TtSession *session, size_t cols, size_t rows);

/**
 * Tell the core how big a character cell is, in pixels. Needed only for
 * mouse reporting; the core learns nothing else about pixels.
 */
void tt_session_set_cell_pixels(TtSession *session, int32_t w, int32_t h);

/**
 * Send a line break — `CommSendBreak`. On a serial console this is how you
 * reach a `getty` or drop a Sun box to its PROM. A no-op with nothing
 * connected.
 */
TtStatus tt_session_send_break(TtSession *session, uint32_t ms);

/**
 * Feed bytes as though they had arrived from the far end.
 *
 * For local echo and for tests, and it is how a replayed session log will
 * work. Queues a [`TtEventKind::Damage`].
 */
void tt_session_feed(TtSession *session, const uint8_t *bytes, size_t len);

/**
 * Fill `out` with Tera Term's own defaults: 9600 8N1, no flow control, DTR
 * and RTS asserted, break detection on.
 */
void tt_serial_params_default(TtSerialParams *out);

/**
 * Open a serial port and attach it. Replaces any current connection.
 *
 * Pass the port's `open_path`, not its `device` — see [`TtPortInfo`].
 *
 * The terminal is **not** reset: reconnecting a serial console to the same
 * session is how you keep the scrollback that explains why it dropped.
 */
TtStatus tt_session_connect_serial(TtSession *session,
                                   const char *path,
                                   const TtSerialParams *params);

/**
 * Fill `out` with the defaults for `port`: upstream's mode rule, 38400 both
 * ways, no `BINARY`, a ten-second connect timeout.
 */
void tt_telnet_params_default(TtTelnetParams *out, uint16_t port);

/**
 * Open a telnet (or raw TCP) connection and attach it. Replaces any current
 * one.
 *
 * Synchronous, unlike [`tt_ssh_connect`], and that is not an inconsistency:
 * telnet asks no questions. There is no host key and no password — the login
 * prompt a server sends is *terminal output*, typed into like any other.
 *
 * The terminal is **not** reset, so reconnecting keeps the scrollback that
 * explains why it dropped.
 */
TtStatus tt_session_connect_telnet(TtSession *session,
                                   const char *host,
                                   uint16_t port,
                                   const TtTelnetParams *params);

/**
 * Fill `out` with the defaults: the user's login shell, their home
 * directory, `xterm-256color`.
 */
void tt_pty_params_default(TtPtyParams *out);

/**
 * Fork a shell onto a local pty and attach it. Replaces any current
 * connection.
 *
 * The size comes from the session rather than from `params`, because the
 * window already knows it and a child that starts at the wrong width draws
 * one wrong prompt before the first resize corrects it.
 *
 * When the child exits, the session reports `TT_EVENT_DISCONNECTED` and
 * [`tt_session_close_note`] says what happened to it.
 */
TtStatus tt_session_connect_pty(TtSession *session,
                                const TtPtyParams *params);

/**
 * Drop the connection. The screen is left alone. A no-op when there is none.
 */
void tt_session_disconnect(TtSession *session);

bool tt_session_is_connected(const TtSession *session);

/**
 * Whether [`tt_session_send_break`] will do anything on the current
 * connection. False when there is none.
 *
 * **For drawing the menu, not for handling the failure.** SSH has no break —
 * RFC 4335 defines one and `russh` does not implement it — so a window that
 * offers the item on an SSH session is offering an error message, and it
 * offers it at the moment a console has stopped answering, which is the worst
 * time to find out.
 */
bool tt_session_supports_break(const TtSession *session);

/**
 * A short name for the status line — `/dev/ttyUSB0`, `user@host`. Null when
 * nothing is connected.
 *
 * Borrowed, and valid until the next call to this function on this session.
 */
const char *tt_session_describe(TtSession *session);

/**
 * Why the last connection ended, when the transport knew something the word
 * "disconnected" does not say — "bash exited with status 1" from a local
 * shell. Null when nothing more is known, which is the usual case.
 *
 * Read it after `TT_EVENT_DISCONNECTED`. It survives until the next
 * [`tt_session_connect_serial`] or friend, so a status line can keep showing
 * it while the window sits there disconnected.
 *
 * Borrowed, and valid until the next call to this function on this session.
 */
const char *tt_session_close_note(TtSession *session);

/**
 * Every serial port the system can see, sorted by device node so a picker
 * does not reshuffle between refreshes. Null on failure.
 */
TtPortList *tt_serial_enumerate(void);

size_t tt_port_list_len(const TtPortList *list);

/**
 * Borrow one entry. Null when `index` is out of range. Valid until the list
 * is freed.
 */
const TtPortInfo *tt_port_list_at(const TtPortList *list, size_t index);

void tt_port_list_free(TtPortList *list);

/**
 * Fill `out` with the sensible defaults: read `~/.ssh/config`, use the agent,
 * ask about unknown host keys, modern algorithms only, 30-second timeout.
 */
void tt_ssh_params_default(TtSshParams *out);

/**
 * Start connecting. Returns immediately, before anything has happened; null
 * only if the thread or the pipe could not be created.
 *
 * The session is **not** passed here. It is passed to
 * [`tt_ssh_connect_poll`], which attaches the transport the moment the shell
 * is running — so nothing stores a `TtSession *` it does not own.
 */
TtSshConnect *tt_ssh_connect(const TtSshParams *params);

/**
 * The descriptor to wait on.
 *
 * **The same one [`tt_session_poll_fd`] returns once the session is
 * connected**, so a frontend registers its notifier once and keeps it across
 * the handover rather than swapping it at the moment output starts.
 */
int tt_ssh_connect_poll_fd(const TtSshConnect *c);

/**
 * What the connection needs next. Never blocks.
 *
 * On [`TT_SSH_READY`] the transport is attached to `session`, replacing
 * whatever was there. `session` may be null only if the caller intends to
 * throw the connection away, in which case `READY` still ends it.
 */
TtSshStep tt_ssh_connect_poll(TtSshConnect *c, TtSession *session);

/**
 * The outstanding host-key question, or null when the last poll did not
 * return [`TT_SSH_HOST_KEY`]. Valid until the next poll.
 */
const TtSshHostKeyPrompt *tt_ssh_connect_host_key(const TtSshConnect *c);

/**
 * The outstanding authentication question, or null when the last poll did
 * not return [`TT_SSH_AUTH`]. Valid until the next poll.
 */
const TtSshAuthPrompt *tt_ssh_connect_auth(const TtSshConnect *c);

/**
 * Answer a [`TT_SSH_HOST_KEY`] with 1 to accept and record, 2 to accept just
 * this once, and anything else to refuse.
 *
 * Deliberately three answers rather than a bool. "Yes, but do not write it
 * down" is what a user on a network they do not trust means, and collapsing
 * it into "yes" silently records a key they did not want recorded.
 */
void tt_ssh_connect_answer_host_key(TtSshConnect *c, int decision);

/**
 * Answer a [`TT_SSH_AUTH`], one string per prompt in the order asked.
 *
 * A short or long list is padded or truncated to what the server asked for
 * rather than passed on: the protocol requires one response per prompt, and
 * getting it wrong desynchronises the exchange in a way that reads as a
 * server bug.
 */
void tt_ssh_connect_answer_auth(TtSshConnect *c,
                                const char *const *answers,
                                size_t count);

/**
 * Stop, and free. Safe on null, and safe after [`TT_SSH_READY`] — the
 * session owns the connection by then and freeing the handle does not touch
 * it.
 */
void tt_ssh_connect_free(TtSshConnect *c);

/**
 * Every `Host` alias in `~/.ssh/config` that names one machine — no
 * wildcards, no negations — for filling a picker. Null on failure.
 *
 * A `Host *` block is not somewhere to connect, and a `!bastion` names a host
 * its block is *about* rather than one it configures. Offering either would
 * put entries in a dropdown that cannot be connected to.
 */
TtStringList *tt_ssh_config_aliases(void);

size_t tt_string_list_len(const TtStringList *list);

/**
 * Borrow one entry. Null when `index` is out of range. Valid until the list
 * is freed.
 */
const char *tt_string_list_at(const TtStringList *list, size_t index);

void tt_string_list_free(TtStringList *list);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* STERNA_H */
