#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Generate Sterna's Markdown TTL reference from the pinned Tera Term manual."""

from __future__ import annotations

import argparse
import html
from html.parser import HTMLParser
import os
from pathlib import Path, PurePosixPath
import re
import subprocess
import sys
from dataclasses import dataclass, field


UPSTREAM_REVISION = "827a35b050c974b0fdf2a77ef73ed882301eb6c4"
MANUAL_BASE = "https://teratermproject.github.io/manual/5/en/html/"
GENERATED = (
    "<!-- Generated by docs/macro/generate.py from Tera Term "
    f"{UPSTREAM_REVISION}; do not edit. -->\n\n"
)
REFERENCE_NOTE = (
    "> Compatibility reference derived from Tera Term. TTL syntax and command "
    "behaviour apply to Sterna; executable and UI instructions describe "
    "upstream.\n\n"
)
VOID = {"br", "hr", "img", "link", "meta"}
AUTOCLOSE = {"dd", "dt", "li", "p", "td", "th", "tr"}


@dataclass
class Node:
    tag: str
    attrs: dict[str, str | None] = field(default_factory=dict)
    children: list[Node | str] = field(default_factory=list)


class TreeParser(HTMLParser):
    """A small forgiving HTML 4 tree builder, enough for the pinned manual."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.root = Node("document")
        self.stack = [self.root]

    def handle_starttag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        tag = tag.lower()
        if tag in AUTOCLOSE:
            for i in range(len(self.stack) - 1, 0, -1):
                if self.stack[i].tag == tag:
                    del self.stack[i:]
                    break
                if self.stack[i].tag in {"body", "dl", "ol", "table", "ul"}:
                    break
        node = Node(tag, {key.lower(): value for key, value in attrs})
        self.stack[-1].children.append(node)
        if tag not in VOID:
            self.stack.append(node)

    def handle_startendtag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        self.handle_starttag(tag, attrs)
        if tag.lower() not in VOID:
            self.handle_endtag(tag)

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        for i in range(len(self.stack) - 1, 0, -1):
            if self.stack[i].tag == tag:
                del self.stack[i:]
                return

    def handle_data(self, data: str) -> None:
        self.stack[-1].children.append(data)


def first(node: Node, tag: str) -> Node | None:
    if node.tag == tag:
        return node
    for child in node.children:
        if isinstance(child, Node):
            found = first(child, tag)
            if found is not None:
                return found
    return None


def plain_text(node: Node) -> str:
    pieces: list[str] = []
    for child in node.children:
        if isinstance(child, str):
            pieces.append(child)
        elif child.tag == "br":
            pieces.append("\n")
        else:
            pieces.append(plain_text(child))
    return "".join(pieces)


class Markdown:
    def __init__(self, page: PurePosixPath) -> None:
        # Path from en/html, for example macro/command/sendln.html.
        self.page = page

    def href(self, value: str) -> str:
        if not value or value.startswith(("#", "http://", "https://", "mailto:")):
            return value.lower() if value.startswith("#") else value

        path, marker, fragment = value.partition("#")
        resolved = PurePosixPath(os.path.normpath(str(self.page.parent / path)))
        suffix = f"#{fragment.lower()}" if marker else ""
        if not str(resolved).startswith("macro/"):
            return MANUAL_BASE + str(resolved) + suffix

        local = PurePosixPath(os.path.relpath(resolved, self.page.parent))
        if local.suffix.lower() == ".html":
            local = (
                local.with_name("README.md")
                if local.name.lower() == "index.html"
                else local.with_suffix(".md")
            )
        return str(local) + suffix

    @staticmethod
    def clean(value: str) -> str:
        value = re.sub(r"[ \t\r\f\v]+", " ", value)
        value = re.sub(r" *\n *", "\n", value)
        return value.strip()

    def inline(self, node: Node) -> str:
        out: list[str] = []
        for child in node.children:
            if isinstance(child, str):
                out.append(html.escape(re.sub(r"\s+", " ", child), quote=False))
                continue
            value = self.inline(child)
            if child.tag == "a":
                href = child.attrs.get("href")
                if href:
                    value = f"[{value.strip()}]({self.href(href)})"
            elif child.tag in {"b", "strong"}:
                value = f"**{value.strip()}**"
            elif child.tag == "em":
                value = f"*{value.strip()}*"
            elif child.tag == "code":
                value = f"`{value.strip()}`"
            elif child.tag == "br":
                value = "  \n"
            elif child.tag == "sup":
                value = f"<sup>{value.strip()}</sup>"
            elif child.tag == "s":
                value = f"~~{value.strip()}~~"
            elif child.tag == "img":
                src = child.attrs.get("src") or ""
                alt = child.attrs.get("alt") or ""
                value = f"![{alt}]({src})"
            out.append(value)
        return self.clean("".join(out))

    def raw_html(self, node: Node) -> str:
        attrs = "".join(
            f' {key}="{html.escape(self.href(value) if key == "href" else value, quote=True)}"'
            if value is not None
            else f" {key}"
            for key, value in node.attrs.items()
        )
        inner = "".join(
            html.escape(child, quote=False)
            if isinstance(child, str)
            else self.raw_html(child)
            for child in node.children
        )
        if node.tag in VOID:
            return f"<{node.tag}{attrs}>"
        return f"<{node.tag}{attrs}>{inner}</{node.tag}>"

    def list(self, node: Node, ordered: bool, depth: int = 0) -> str:
        lines: list[str] = []
        items = [c for c in node.children if isinstance(c, Node) and c.tag == "li"]
        for number, item in enumerate(items, 1):
            nested = [
                c for c in item.children if isinstance(c, Node) and c.tag in {"ul", "ol"}
            ]
            shell = Node(
                "li",
                children=[c for c in item.children if c not in nested],
            )
            value = self.inline(shell).strip()
            prefix = f"{number}. " if ordered else "- "
            indent = "  " * depth
            lines.append(indent + prefix + value)
            for child in nested:
                lines.append(self.list(child, child.tag == "ol", depth + 1).rstrip())
        return "\n".join(lines) + "\n\n"

    def definition_list(self, node: Node) -> str:
        out: list[str] = []
        term = ""
        for child in node.children:
            if not isinstance(child, Node):
                continue
            if child.tag == "dt":
                term = self.inline(child)
            elif child.tag == "dd":
                if term:
                    out.append(f"**{term}**")
                out.append(self.inline(child))
                term = ""
        return "\n\n".join(out) + "\n\n"

    def block(self, node: Node) -> str:
        if node.tag in {"document", "body"}:
            return "".join(
                self.block(child) if isinstance(child, Node) else ""
                for child in node.children
            )
        if node.tag in {"head", "script", "style"}:
            return ""
        if node.tag in {"h1", "h2", "h3"}:
            level = int(node.tag[1])
            return f"{'#' * level} {self.inline(node)}\n\n"
        if node.tag == "div" and node.attrs.get("class") == "topic":
            return f"## {self.inline(node)}\n\n"
        if node.tag == "p":
            value = self.inline(node)
            return f"{value}\n\n" if value else ""
        if node.tag == "pre":
            value = plain_text(node).strip("\r\n").replace("\r\n", "\n")
            language = (
                "ttl"
                if (node.attrs.get("class") or "").startswith("macro-")
                else "text"
            )
            return f"```{language}\n{value}\n```\n\n"
        if node.tag == "ul":
            return self.list(node, False)
        if node.tag == "ol":
            return self.list(node, True)
        if node.tag == "dl":
            return self.definition_list(node)
        if node.tag == "table":
            return self.raw_html(node).strip() + "\n\n"
        if node.tag == "hr":
            return "---\n\n"
        value = self.inline(node)
        return f"{value}\n\n" if value else ""

    def page_body(self, root: Node) -> str:
        body = first(root, "body")
        if body is None:
            raise ValueError(f"{self.page}: no body")
        value = self.block(body)
        value = re.sub(r"\n{3,}", "\n\n", value).strip()
        value = "\n".join(line.rstrip() for line in value.splitlines())
        return value + "\n"


def parse_html(path: Path) -> Node:
    parser = TreeParser()
    parser.feed(path.read_text(encoding="iso-8859-1"))
    parser.close()
    return parser.root


def command_table(path: Path) -> dict[str, str]:
    source = path.read_text(encoding="utf-8")
    operator_body = source.split("pub fn is_operator", 1)[1].split("/// Every", 1)[0]
    operators = set(re.findall(r"Rsv::(\w+)", operator_body))

    commands: dict[str, str] = {}
    feature_gated = False
    for line in source.splitlines():
        stripped = line.strip()
        if stripped.startswith("#[cfg("):
            feature_gated = True
            continue
        found = re.fullmatch(r'\("([^"]+)", Rsv::(\w+)\),', stripped)
        if found:
            name, variant = found.groups()
            if not feature_gated and variant not in operators:
                commands[name] = variant
            feature_gated = False
        elif stripped and not stripped.startswith("//"):
            feature_gated = False
    if not commands:
        raise ValueError(f"{path}: no command words")
    return commands


def command_index(root: Node, commands: dict[str, str]) -> str:
    body = first(root, "body")
    if body is None:
        raise ValueError("command/index.html: no body")

    sections: list[tuple[str, Node]] = []
    heading: str | None = None
    for child in body.children:
        if not isinstance(child, Node):
            continue
        if child.tag == "h2":
            heading = Markdown(PurePosixPath("macro/command/index.html")).inline(child)
        elif child.tag == "ul" and heading is not None:
            sections.append((heading, child))
            heading = None

    markdown = Markdown(PurePosixPath("macro/command/index.html"))
    documented: dict[str, str] = {}
    rendered: list[str] = []
    for heading, listing in sections:
        rendered.append(f"## {heading}\n")
        for item in [
            child
            for child in listing.children
            if isinstance(child, Node) and child.tag == "li"
        ]:
            link = first(item, "a")
            if link is None or not link.attrs.get("href"):
                continue
            names = [name.strip().lower() for name in plain_text(link).split(",")]
            for name in names:
                if name in documented:
                    raise ValueError(f"command index documents {name!r} twice")
                documented[name] = link.attrs["href"] or ""
            rendered.append(f"- {markdown.inline(item)}")
        rendered.append("")

    missing = sorted(set(commands) - set(documented))
    extra = sorted(set(documented) - set(commands))
    if missing or extra:
        raise ValueError(
            "command index and tt-ttl disagree: "
            f"missing documentation={missing}, undocumented implementation={extra}"
        )

    implementations = len(set(commands.values()))
    introduction = f"""# TTL command reference

This index contains the {len(commands)} command spellings accepted by Sterna's
default TTL interpreter, backed by {implementations} command implementations.
It is generated from [`rsv.rs`](../../../crates/tt-ttl/src/rsv.rs); adding a
command without documenting it makes generation fail.

The individual pages are mechanically converted from the English Tera Term
manual at the revision named in the generated-file header. TTL runs inside
Sterna rather than in `TTPMACRO.EXE`, but its command syntax and observable
behaviour are kept compatible.

"""
    return introduction + "\n".join(rendered).rstrip() + "\n"


def expected_files(source: Path, rsv: Path) -> dict[Path, bytes]:
    commands = command_table(rsv)
    expected: dict[Path, bytes] = {}
    command_root: Node | None = None

    for html_path in sorted(source.rglob("*.html")):
        relative = html_path.relative_to(source)
        output = (
            relative.with_name("README.md")
            if relative.name.lower() == "index.html"
            else relative.with_suffix(".md")
        )
        page = PurePosixPath("macro") / PurePosixPath(relative.as_posix())
        root = parse_html(html_path)
        if relative == Path("command/index.html"):
            command_root = root
            continue
        expected[output] = (
            GENERATED + REFERENCE_NOTE + Markdown(page).page_body(root)
        ).encode()

    if command_root is None:
        raise ValueError(f"{source}: no command/index.html")
    expected[Path("command/README.md")] = (
        GENERATED + REFERENCE_NOTE + command_index(command_root, commands)
    ).encode()

    for image in sorted(source.rglob("*.png")):
        expected[image.relative_to(source)] = image.read_bytes()
    return expected


def check_revision(source: Path) -> None:
    repository = source.parents[3]
    try:
        actual = subprocess.check_output(
            ["git", "-C", repository, "rev-parse", "HEAD"], text=True
        ).strip()
    except (OSError, subprocess.CalledProcessError) as error:
        raise SystemExit(f"cannot identify Tera Term checkout: {error}") from error
    if actual != UPSTREAM_REVISION:
        raise SystemExit(
            "Tera Term checkout is not the pinned documentation source:\n"
            f"  expected {UPSTREAM_REVISION}\n  actual   {actual}"
        )


def compare(output: Path, expected: dict[Path, bytes]) -> list[str]:
    changed: list[str] = []
    for relative, content in expected.items():
        path = output / relative
        if not path.is_file() or path.read_bytes() != content:
            changed.append(str(relative))

    existing = {
        path.relative_to(output)
        for pattern in ("*.md", "*.png")
        for path in output.rglob(pattern)
    }
    changed.extend(f"{path} (stale)" for path in sorted(existing - set(expected)))
    return changed


def write(output: Path, expected: dict[Path, bytes]) -> None:
    output.mkdir(parents=True, exist_ok=True)
    existing = {
        path.relative_to(output)
        for pattern in ("*.md", "*.png")
        for path in output.rglob(pattern)
    }
    for stale in existing - set(expected):
        (output / stale).unlink()
    for relative, content in expected.items():
        path = output / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)


def main() -> int:
    project = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    parser.add_argument(
        "--source",
        type=Path,
        default=project.parent / "teraterm/doc/en/html/macro",
        help="upstream English macro manual",
    )
    parser.add_argument(
        "--output", type=Path, default=project / "docs/macro", help="generated tree"
    )
    args = parser.parse_args()
    source = args.source.resolve()
    output = args.output.resolve()
    if not source.is_dir():
        parser.error(f"source directory does not exist: {source}")
    check_revision(source)

    try:
        expected = expected_files(source, project / "crates/tt-ttl/src/rsv.rs")
    except ValueError as error:
        raise SystemExit(str(error)) from error
    changed = compare(output, expected)
    if args.check:
        if changed:
            print("macro reference is stale:", file=sys.stderr)
            for path in changed:
                print(f"  {path}", file=sys.stderr)
            return 1
        print(f"macro reference ok ({len(expected)} files)")
        return 0

    write(output, expected)
    print(f"wrote {len(expected)} files to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
