// Reserved words, transcribed from `ttmparse.cpp:CheckReservedWord` (:176-450).
//
// Upstream is a hand-written `switch` on the first letter followed by a chain
// of `_stricmp`, and the numeric ids it assigns are its own; only the mapping
// from name to command matters here. The names are ASCII and the comparison is
// case-insensitive, so the table is sorted and binary-searched.
//
// `setspeed` and `setbaud` are two names for one command, which is why the
// table is longer than the enum.

/// A reserved word: every TTL command, plus the operators that have a name.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Rsv {
    Basename,
    Beep,
    BPlusRecv,
    BPlusSend,
    Break,
    BringupBox,
    Call,
    CallMenu,
    ChangeDir,
    Checksum16,
    Checksum16File,
    Checksum32,
    Checksum32File,
    Checksum8,
    Checksum8File,
    ClearScreen,
    Clipb2Var,
    CloseSBox,
    CloseTT,
    Code2Str,
    Connect,
    Continue,
    Crc16,
    Crc16File,
    Crc32,
    Crc32File,
    CygConnect,
    DelPassword,
    DelPassword2,
    Dirname,
    DirnameBox,
    Disconnect,
    DispStr,
    Do,
    Else,
    ElseIf,
    EnableKeyb,
    End,
    EndIf,
    EndUntil,
    EndWhile,
    Exec,
    ExecCmnd,
    Exit,
    ExpandEnv,
    FileClose,
    FileConcat,
    FileCopy,
    FileCreate,
    FileDelete,
    FileLock,
    FileMarkPtr,
    FileOpen,
    FileRead,
    FileReadln,
    FileRename,
    FileSearch,
    FileSeek,
    FileSeekBack,
    FileStat,
    FileStrSeek,
    FileStrSeek2,
    FileTruncate,
    FileUnLock,
    FileWrite,
    FileWriteLn,
    FindClose,
    FindFirst,
    FindNext,
    FlushRecv,
    FolderCreate,
    FolderDelete,
    FolderSearch,
    For,
    GetDate,
    GetDir,
    GetEnv,
    GetFileAttr,
    GetHostname,
    GetIPv4Addr,
    GetIPv6Addr,
    GetModemStatus,
    GetPassword,
    GetPassword2,
    GetSpecialFolder,
    GetTime,
    GetTitle,
    GetTTDir,
    GetTTPos,
    GetVer,
    Goto,
    If,
    IfDefined,
    Include,
    InputBox,
    Int2Str,
    IntDim,
    IsPassword,
    IsPassword2,
    KmtFinish,
    KmtGet,
    KmtRecv,
    KmtSend,
    ListBox,
    LoadKeyMap,
    LogAutoClose,
    LogClose,
    LogInfo,
    LogOpen,
    LogPause,
    LogRotate,
    LogStart,
    LogWrite,
    Loop,
    MakePath,
    MessageBox,
    MilliPause,
    Next,
    OutputDebugString,
    PasswordBox,
    Pause,
    QuickVANRecv,
    QuickVANSend,
    Random,
    RecvFile,
    RecvLn,
    RegexOption,
    RestoreSetup,
    Return,
    RotateL,
    RotateR,
    ScpRecv,
    ScpSend,
    Send,
    SendBinary,
    SendBreak,
    SendBroadcast,
    SendFile,
    SendKCode,
    SendLn,
    SendlnBroadcast,
    SendlnMulticast,
    SendMulticast,
    SendText,
    SetBaud,
    SetDate,
    SetDebug,
    SetDir,
    SetDlgPos,
    SetDtr,
    SetEcho,
    SetEnv,
    SetExitCode,
    SetFileAttr,
    SetFlowCtrl,
    SetMulticastName,
    SetPassword,
    SetPassword2,
    SetRts,
    SetSerialDelayChar,
    SetSerialDelayLine,
    SetSync,
    SetTime,
    SetTitle,
    Show,
    ShowTT,
    Sprintf,
    Sprintf2,
    StatusBox,
    Str2Code,
    Str2Int,
    StrCompare,
    StrConcat,
    StrCopy,
    StrDim,
    StrInsert,
    StrJoin,
    StrLen,
    StrMatch,
    StrRemove,
    StrReplace,
    StrScan,
    StrSpecial,
    StrSplit,
    StrTrim,
    TestLink,
    Then,
    ToLower,
    ToUpper,
    Unlink,
    Until,
    Uptime,
    Var2Clipb,
    Wait,
    Wait4all,
    WaitEvent,
    WaitLn,
    WaitN,
    WaitRecv,
    WaitRegex,
    While,
    XmodemRecv,
    XmodemSend,
    YesNoBox,
    YmodemRecv,
    YmodemSend,
    ZmodemRecv,
    ZmodemSend,

    // Operators. `GetOperator` (`ttmparse.cpp:626`) accepts these both as
    // punctuation and, for the four named ones, as identifiers — and refuses
    // anything below `RsvOperator`, which is what `is_operator` reproduces.
    /// `~ / not`
    BNot,
    /// `& / and`
    BAnd,
    /// `| / or`
    BOr,
    /// `^ / xor`
    BXor,
    /// `*`
    Mul,
    /// `+`
    Plus,
    /// `-`
    Minus,
    /// `/`
    Div,
    /// `%`
    Mod,
    /// `<`
    Lt,
    /// `= / ==`
    Eq,
    /// `>`
    Gt,
    /// `<=`
    Le,
    /// `<> / !=`
    Ne,
    /// `>=`
    Ge,
    /// `!`
    LNot,
    /// `&&`
    LAnd,
    /// `||`
    LOr,
    /// `(none)`
    LXor,
    /// `>>`
    ARShift,
    /// `<<`
    ALShift,
    /// `>>>`
    LRShift,
}

impl Rsv {
    /// Whether this is one of the operator words — upstream's `>= RsvOperator`.
    pub fn is_operator(self) -> bool {
        matches!(
            self,
            Rsv::BNot
                | Rsv::BAnd
                | Rsv::BOr
                | Rsv::BXor
                | Rsv::Mul
                | Rsv::Plus
                | Rsv::Minus
                | Rsv::Div
                | Rsv::Mod
                | Rsv::Lt
                | Rsv::Eq
                | Rsv::Gt
                | Rsv::Le
                | Rsv::Ne
                | Rsv::Ge
                | Rsv::LNot
                | Rsv::LAnd
                | Rsv::LOr
                | Rsv::LXor
                | Rsv::ARShift
                | Rsv::ALShift
                | Rsv::LRShift
        )
    }
}

/// Every reserved word by name, sorted for binary search.
pub(crate) static RESERVED: &[(&str, Rsv)] = &[
    ("and", Rsv::BAnd),
    ("basename", Rsv::Basename),
    ("beep", Rsv::Beep),
    ("bplusrecv", Rsv::BPlusRecv),
    ("bplussend", Rsv::BPlusSend),
    ("break", Rsv::Break),
    ("bringupbox", Rsv::BringupBox),
    ("call", Rsv::Call),
    ("callmenu", Rsv::CallMenu),
    ("changedir", Rsv::ChangeDir),
    ("checksum16", Rsv::Checksum16),
    ("checksum16file", Rsv::Checksum16File),
    ("checksum32", Rsv::Checksum32),
    ("checksum32file", Rsv::Checksum32File),
    ("checksum8", Rsv::Checksum8),
    ("checksum8file", Rsv::Checksum8File),
    ("clearscreen", Rsv::ClearScreen),
    ("clipb2var", Rsv::Clipb2Var),
    ("closesbox", Rsv::CloseSBox),
    ("closett", Rsv::CloseTT),
    ("code2str", Rsv::Code2Str),
    ("connect", Rsv::Connect),
    ("continue", Rsv::Continue),
    ("crc16", Rsv::Crc16),
    ("crc16file", Rsv::Crc16File),
    ("crc32", Rsv::Crc32),
    ("crc32file", Rsv::Crc32File),
    ("cygconnect", Rsv::CygConnect),
    ("delpassword", Rsv::DelPassword),
    ("delpassword2", Rsv::DelPassword2),
    ("dirname", Rsv::Dirname),
    ("dirnamebox", Rsv::DirnameBox),
    ("disconnect", Rsv::Disconnect),
    ("dispstr", Rsv::DispStr),
    ("do", Rsv::Do),
    ("else", Rsv::Else),
    ("elseif", Rsv::ElseIf),
    ("enablekeyb", Rsv::EnableKeyb),
    ("end", Rsv::End),
    ("endif", Rsv::EndIf),
    ("enduntil", Rsv::EndUntil),
    ("endwhile", Rsv::EndWhile),
    ("exec", Rsv::Exec),
    ("execcmnd", Rsv::ExecCmnd),
    ("exit", Rsv::Exit),
    ("expandenv", Rsv::ExpandEnv),
    ("fileclose", Rsv::FileClose),
    ("fileconcat", Rsv::FileConcat),
    ("filecopy", Rsv::FileCopy),
    ("filecreate", Rsv::FileCreate),
    ("filedelete", Rsv::FileDelete),
    ("filelock", Rsv::FileLock),
    ("filemarkptr", Rsv::FileMarkPtr),
    ("fileopen", Rsv::FileOpen),
    ("fileread", Rsv::FileRead),
    ("filereadln", Rsv::FileReadln),
    ("filerename", Rsv::FileRename),
    ("filesearch", Rsv::FileSearch),
    ("fileseek", Rsv::FileSeek),
    ("fileseekback", Rsv::FileSeekBack),
    ("filestat", Rsv::FileStat),
    ("filestrseek", Rsv::FileStrSeek),
    ("filestrseek2", Rsv::FileStrSeek2),
    ("filetruncate", Rsv::FileTruncate),
    ("fileunlock", Rsv::FileUnLock),
    ("filewrite", Rsv::FileWrite),
    ("filewriteln", Rsv::FileWriteLn),
    ("findclose", Rsv::FindClose),
    ("findfirst", Rsv::FindFirst),
    ("findnext", Rsv::FindNext),
    ("flushrecv", Rsv::FlushRecv),
    ("foldercreate", Rsv::FolderCreate),
    ("folderdelete", Rsv::FolderDelete),
    ("foldersearch", Rsv::FolderSearch),
    ("for", Rsv::For),
    ("getdate", Rsv::GetDate),
    ("getdir", Rsv::GetDir),
    ("getenv", Rsv::GetEnv),
    ("getfileattr", Rsv::GetFileAttr),
    ("gethostname", Rsv::GetHostname),
    ("getipv4addr", Rsv::GetIPv4Addr),
    ("getipv6addr", Rsv::GetIPv6Addr),
    ("getmodemstatus", Rsv::GetModemStatus),
    ("getpassword", Rsv::GetPassword),
    ("getpassword2", Rsv::GetPassword2),
    ("getspecialfolder", Rsv::GetSpecialFolder),
    ("gettime", Rsv::GetTime),
    ("gettitle", Rsv::GetTitle),
    ("getttdir", Rsv::GetTTDir),
    ("getttpos", Rsv::GetTTPos),
    ("getver", Rsv::GetVer),
    ("goto", Rsv::Goto),
    ("if", Rsv::If),
    ("ifdefined", Rsv::IfDefined),
    ("include", Rsv::Include),
    ("inputbox", Rsv::InputBox),
    ("int2str", Rsv::Int2Str),
    ("intdim", Rsv::IntDim),
    ("ispassword", Rsv::IsPassword),
    ("ispassword2", Rsv::IsPassword2),
    ("kmtfinish", Rsv::KmtFinish),
    ("kmtget", Rsv::KmtGet),
    ("kmtrecv", Rsv::KmtRecv),
    ("kmtsend", Rsv::KmtSend),
    ("listbox", Rsv::ListBox),
    ("loadkeymap", Rsv::LoadKeyMap),
    ("logautoclosemode", Rsv::LogAutoClose),
    ("logclose", Rsv::LogClose),
    ("loginfo", Rsv::LogInfo),
    ("logopen", Rsv::LogOpen),
    ("logpause", Rsv::LogPause),
    ("logrotate", Rsv::LogRotate),
    ("logstart", Rsv::LogStart),
    ("logwrite", Rsv::LogWrite),
    ("loop", Rsv::Loop),
    ("makepath", Rsv::MakePath),
    ("messagebox", Rsv::MessageBox),
    ("mpause", Rsv::MilliPause),
    ("next", Rsv::Next),
    ("not", Rsv::BNot),
    ("or", Rsv::BOr),
    ("outputdebugstring", Rsv::OutputDebugString),
    ("passwordbox", Rsv::PasswordBox),
    ("pause", Rsv::Pause),
    ("quickvanrecv", Rsv::QuickVANRecv),
    ("quickvansend", Rsv::QuickVANSend),
    ("random", Rsv::Random),
    ("recvfile", Rsv::RecvFile),
    ("recvln", Rsv::RecvLn),
    ("regexoption", Rsv::RegexOption),
    ("restoresetup", Rsv::RestoreSetup),
    ("return", Rsv::Return),
    ("rotateleft", Rsv::RotateL),
    ("rotateright", Rsv::RotateR),
    ("scprecv", Rsv::ScpRecv),
    ("scpsend", Rsv::ScpSend),
    ("send", Rsv::Send),
    ("sendbinary", Rsv::SendBinary),
    ("sendbreak", Rsv::SendBreak),
    ("sendbroadcast", Rsv::SendBroadcast),
    ("sendfile", Rsv::SendFile),
    ("sendkcode", Rsv::SendKCode),
    ("sendln", Rsv::SendLn),
    ("sendlnbroadcast", Rsv::SendlnBroadcast),
    ("sendlnmulticast", Rsv::SendlnMulticast),
    ("sendmulticast", Rsv::SendMulticast),
    ("sendtext", Rsv::SendText),
    ("setbaud", Rsv::SetBaud),
    ("setdate", Rsv::SetDate),
    ("setdebug", Rsv::SetDebug),
    ("setdir", Rsv::SetDir),
    ("setdlgpos", Rsv::SetDlgPos),
    ("setdtr", Rsv::SetDtr),
    ("setecho", Rsv::SetEcho),
    ("setenv", Rsv::SetEnv),
    ("setexitcode", Rsv::SetExitCode),
    ("setfileattr", Rsv::SetFileAttr),
    ("setflowctrl", Rsv::SetFlowCtrl),
    ("setmulticastname", Rsv::SetMulticastName),
    ("setpassword", Rsv::SetPassword),
    ("setpassword2", Rsv::SetPassword2),
    ("setrts", Rsv::SetRts),
    ("setserialdelaychar", Rsv::SetSerialDelayChar),
    ("setserialdelayline", Rsv::SetSerialDelayLine),
    ("setspeed", Rsv::SetBaud),
    ("setsync", Rsv::SetSync),
    ("settime", Rsv::SetTime),
    ("settitle", Rsv::SetTitle),
    ("show", Rsv::Show),
    ("showtt", Rsv::ShowTT),
    ("sprintf", Rsv::Sprintf),
    ("sprintf2", Rsv::Sprintf2),
    ("statusbox", Rsv::StatusBox),
    ("str2code", Rsv::Str2Code),
    ("str2int", Rsv::Str2Int),
    ("strcompare", Rsv::StrCompare),
    ("strconcat", Rsv::StrConcat),
    ("strcopy", Rsv::StrCopy),
    ("strdim", Rsv::StrDim),
    ("strinsert", Rsv::StrInsert),
    ("strjoin", Rsv::StrJoin),
    ("strlen", Rsv::StrLen),
    ("strmatch", Rsv::StrMatch),
    ("strremove", Rsv::StrRemove),
    ("strreplace", Rsv::StrReplace),
    ("strscan", Rsv::StrScan),
    ("strspecial", Rsv::StrSpecial),
    ("strsplit", Rsv::StrSplit),
    ("strtrim", Rsv::StrTrim),
    ("testlink", Rsv::TestLink),
    ("then", Rsv::Then),
    ("tolower", Rsv::ToLower),
    ("toupper", Rsv::ToUpper),
    ("unlink", Rsv::Unlink),
    ("until", Rsv::Until),
    ("uptime", Rsv::Uptime),
    ("var2clipb", Rsv::Var2Clipb),
    ("wait", Rsv::Wait),
    ("wait4all", Rsv::Wait4all),
    ("waitevent", Rsv::WaitEvent),
    ("waitln", Rsv::WaitLn),
    ("waitn", Rsv::WaitN),
    ("waitrecv", Rsv::WaitRecv),
    ("waitregex", Rsv::WaitRegex),
    ("while", Rsv::While),
    ("xmodemrecv", Rsv::XmodemRecv),
    ("xmodemsend", Rsv::XmodemSend),
    ("xor", Rsv::BXor),
    ("yesnobox", Rsv::YesNoBox),
    ("ymodemrecv", Rsv::YmodemRecv),
    ("ymodemsend", Rsv::YmodemSend),
    ("zmodemrecv", Rsv::ZmodemRecv),
    ("zmodemsend", Rsv::ZmodemSend),
];
