/*
 * termitta oracle -- GENERATED by gen_stubs.py. Do not edit by hand.
 *
 * No-op definitions for symbols vtterm.c/buffer.c reference but whose
 * translation units the oracle does not compile (GDI rendering, DDE,
 * comm, printing, clipboard). Signatures are lifted from Tera Term's
 * own headers so they cannot drift.
 *
 * Anything the grid model actually observes is hand-written in
 * stubs_manual.c instead; those symbols are excluded automatically by
 * reading build/stubs_manual.o, so the two layers cannot collide.
 */
#include <windows.h>
#include <stddef.h>

#include "teraterm.h"
#include "tttypes.h"
#include "buffer.h"
#include "vtdisp.h"

/* ---- functions ---- */
int b64decode(PCHAR dst, int dsize, PCHAR src)
{
	return 0;
}

BOOL BPStartReceive(BOOL macro, BOOL autostart)
{
	return 0;
}

BOOL CanUseIME(void)
{
	return 0;
}

void CaretOff(vtdraw_t *vt)
{
}

void CaretOn(vtdraw_t *vt)
{
}

BOOL CBSetTextW(HWND hWnd, const wchar_t *str_w, size_t str_len)
{
	return 0;
}

void CBStartPasteB64(HWND HWin, PCHAR header, PCHAR footer)
{
}

void ChangeCaret(vtdraw_t *vt)
{
}

void ClearUserKey()
{
}

void ClosePrnFile(PrintFile *handle, void (*finish_callback)(PrintFile *handle))
{
}

WORD CodeConvJIS2SJIS(WORD KCode)
{
	return 0;
}

WORD CodeConvSJIS2EUC(WORD KCode)
{
	return 0;
}

WORD CodeConvSJIS2JIS(WORD KCode)
{
	return 0;
}

void CommResetSerial(PTTSet ts, PComVar cv, BOOL ClearBuffer)
{
}

BYTE ConvHexChar(BYTE b)
{
	return 0;
}

int DDEGetCount(void)
{
	return 0;
}

void DDEPut1(BYTE b)
{
}

void DefineUserKey(int NewKeyId, PCHAR NewKeyStr, int NewKeyLen)
{
}

void DispChangeBackground(vtdraw_t *vt)
{
}

void DispChangeWin(vtdraw_t *vt)
{
}

void DispClearWin(vtdraw_t *vt)
{
}

void DispConvScreenToWin(vtdraw_t *vt, int Xs, int Ys, int *Xw, int *Yw)
{
}

void DispConvWinToScreen(vtdraw_t *vt, int Xw, int Yw, int *Xs, int *Ys, PBOOL Right)
{
}

void DispCountScroll(vtdraw_t *vt, int n)
{
}

HDC DispDCGetRawDC(ttdc_t *dc)
{
	return 0;
}

BOOL DispDCIsPrinter(ttdc_t *dc)
{
	return 0;
}

BOOL DispDeleteLines(vtdraw_t *vt, int Count, int YEnd)
{
	return 0;
}

void DispEnableCaret(vtdraw_t *vt, BOOL On)
{
}

ttdc_t *DispInitDC(vtdraw_t *vt)
{
	return NULL;
}

BOOL DispInsertLines(vtdraw_t *vt, int Count, int YEnd)
{
	return 0;
}

void DispMoveWindow(vtdraw_t *vt, int x, int y)
{
}

BOOL DispPrnIsNextPage(vtdraw_t *vt, ttdc_t *dc)
{
	return 0;
}

void DispReleaseDC(vtdraw_t *vt, ttdc_t *dc)
{
}

void DispReset(vtdraw_t *vt)
{
}

void DispResizeWin(vtdraw_t *vt, int w, int h)
{
}

void DispScrollHomePos(vtdraw_t *vt)
{
}

void DispScrollNLines(vtdraw_t *vt, int Top, int Bottom, int Direction)
{
}

void DispScrollToCursor(vtdraw_t *vt, int CurX, int CurY)
{
}

void DispSetCaretWidth(BOOL DW)
{
}

void DispSetDrawPos(vtdraw_t *vt, ttdc_t *dc, int x, int y)
{
}

void DispSetupDC(vtdraw_t *vt, ttdc_t *dc, const TCharAttr *Attr, BOOL Reverse)
{
}

void DispShowWindow(vtdraw_t *vt, int mode)
{
}

void DispStrA(vtdraw_t *vt, ttdc_t *dc, const char *Buff, const char *WidthInfo, int Count)
{
}

void DispStrW(vtdraw_t *vt, ttdc_t *dc, const wchar_t *StrW, const char *WidthInfo, int Count)
{
}

void DispUpdateScroll(vtdraw_t *vt)
{
}

int FLogGetFreeCount(void)
{
	return 0;
}

BOOL FLogIsOpend(void)
{
	return 0;
}

BOOL FLogIsOpendText(void)
{
	return 0;
}

void FLogPutUTF32(unsigned int u32)
{
}

wchar_t* FLogTimeStampStrW(enum LogTimestampType timestamp_type, const wchar_t* format, DWORD start_time, DWORD connected_time)
{
	return NULL;
}

size_t GetI18nStrWW(const char *section, const char *key, const wchar_t *def, const wchar_t *iniFile, wchar_t **buf)
{
	return 0;
}

BOOL GetIMEOpenStatus(HWND hWnd)
{
	return 0;
}

DWORD GetPrivateProfileOnOffW(const wchar_t *section, const wchar_t *key, const wchar_t *filenameW, BOOL def, BOOL *val)
{
	return 0;
}

DWORD hGetPrivateProfileStringW(const wchar_t *section, const wchar_t *key, const wchar_t *def, const wchar_t *ini, wchar_t **str)
{
	return 0;
}

BOOL IsCaretEnabled(void)
{
	return 0;
}

BOOL IsCaretOn(void)
{
	return 0;
}

BOOL IsLineVisible(vtdraw_t *vt, int *X, int *Y)
{
	return 0;
}

int __ismbblead(BYTE b, int code_page)
{
	return 0;
}

BOOL IsRelativePathW(const wchar_t *path)
{
	return 0;
}

unsigned int MBCP_UTF32(unsigned short mb_code, int code_page)
{
	return 0;
}

PrintFile *OpenPrnFile(void)
{
	return NULL;
}

BOOL PrnCheckAbort()
{
	return 0;
}

void PrnFinish(PrintFile *handle)
{
}

void SetIMEOpenStatus(HWND hWnd, BOOL stat)
{
}

void TelChangeEcho(void)
{
}

void TelInformWinSize(int nx, int ny)
{
}

void TTXSetWinSize(int rows, int cols)
{
}

void UpdateCaretPosition(vtdraw_t *vt, BOOL enforce)
{
}

size_t UTF16ToUTF32(const wchar_t *wstr_ptr, size_t wstr_len, unsigned int *u32)
{
	return 0;
}

void VTPrintEnd(vtdraw_t *vt, ttdc_t *dc)
{
}

vtdraw_t *VTPrintInit(int PrnFlag, ttdc_t **dc, int *mode)
{
	return NULL;
}

void WriteToPrnFile(PrintFile *handle, BYTE b, BOOL Write)
{
}

void WriteToPrnFileUTF32(PrintFile *handle, unsigned int u32, BOOL Write)
{
}

BOOL ZMODEMStartReceive(BOOL macro, BOOL autostart)
{
	return 0;
}

BOOL ZMODEMStartSend(const wchar_t *fiename, WORD ParamBinaryFlag, BOOL autostart)
{
	return 0;
}

